// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: contract/v1/contract.proto

// 不可变契约（Immutable Contracts）
// 单一真源：CallContext / CallTarget / CallResult / CallEvent
// 规格见 docs/dev/architecture/插件契约与协议.md 第三章

package contractv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 调用方种类（第三章 §3.5，CallerKind 登记）
type CallerKind int32

const (
	CallerKind_CALLER_KIND_UNSPECIFIED CallerKind = 0
	CallerKind_CALLER_KIND_USER        CallerKind = 1
	CallerKind_CALLER_KIND_AGENT       CallerKind = 2
	CallerKind_CALLER_KIND_PLUGIN      CallerKind = 3
	CallerKind_CALLER_KIND_SYSTEM      CallerKind = 4
	CallerKind_CALLER_KIND_RUNNER      CallerKind = 5
)

// Enum value maps for CallerKind.
var (
	CallerKind_name = map[int32]string{
		0: "CALLER_KIND_UNSPECIFIED",
		1: "CALLER_KIND_USER",
		2: "CALLER_KIND_AGENT",
		3: "CALLER_KIND_PLUGIN",
		4: "CALLER_KIND_SYSTEM",
		5: "CALLER_KIND_RUNNER",
	}
	CallerKind_value = map[string]int32{
		"CALLER_KIND_UNSPECIFIED": 0,
		"CALLER_KIND_USER":        1,
		"CALLER_KIND_AGENT":       2,
		"CALLER_KIND_PLUGIN":      3,
		"CALLER_KIND_SYSTEM":      4,
		"CALLER_KIND_RUNNER":      5,
	}
)

func (x CallerKind) Enum() *CallerKind {
	p := new(CallerKind)
	*p = x
	return p
}

func (x CallerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_v1_contract_proto_enumTypes[0].Descriptor()
}

func (CallerKind) Type() protoreflect.EnumType {
	return &file_contract_v1_contract_proto_enumTypes[0]
}

func (x CallerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallerKind.Descriptor instead.
func (CallerKind) EnumDescriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{0}
}

type CallResult_Status int32

const (
	CallResult_STATUS_UNSPECIFIED CallResult_Status = 0
	CallResult_STATUS_OK          CallResult_Status = 1
	CallResult_STATUS_ERROR       CallResult_Status = 2
	CallResult_STATUS_PARTIAL     CallResult_Status = 3
)

// Enum value maps for CallResult_Status.
var (
	CallResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_PARTIAL",
	}
	CallResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_PARTIAL":     3,
	}
)

func (x CallResult_Status) Enum() *CallResult_Status {
	p := new(CallResult_Status)
	*p = x
	return p
}

func (x CallResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_v1_contract_proto_enumTypes[1].Descriptor()
}

func (CallResult_Status) Type() protoreflect.EnumType {
	return &file_contract_v1_contract_proto_enumTypes[1]
}

func (x CallResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallResult_Status.Descriptor instead.
func (CallResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{9, 0}
}

// 统一身份（第三章 §3.6）
type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SystemRoles   []string               `protobuf:"bytes,5,rep,name=system_roles,json=systemRoles,proto3" json:"system_roles,omitempty"`
	ProjectRoles  map[string]*RoleList   `protobuf:"bytes,6,rep,name=project_roles,json=projectRoles,proto3" json:"project_roles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {project_id: [role_id...]}
	SessionId     *string                `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_contract_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Principal) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Principal) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Principal) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Principal) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Principal) GetSystemRoles() []string {
	if x != nil {
		return x.SystemRoles
	}
	return nil
}

func (x *Principal) GetProjectRoles() map[string]*RoleList {
	if x != nil {
		return x.ProjectRoles
	}
	return nil
}

func (x *Principal) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

type RoleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleList) Reset() {
	*x = RoleList{}
	mi := &file_contract_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleList) ProtoMessage() {}

func (x *RoleList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleList.ProtoReflect.Descriptor instead.
func (*RoleList) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *RoleList) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Caller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CallerKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=vastplan.contract.v1.CallerKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caller) Reset() {
	*x = Caller{}
	mi := &file_contract_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caller) ProtoMessage() {}

func (x *Caller) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caller.ProtoReflect.Descriptor instead.
func (*Caller) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *Caller) GetKind() CallerKind {
	if x != nil {
		return x.Kind
	}
	return CallerKind_CALLER_KIND_UNSPECIFIED
}

func (x *Caller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 链路追踪
type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  *string                `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3,oneof" json:"parent_span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_contract_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *Trace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Trace) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Trace) GetParentSpanId() string {
	if x != nil && x.ParentSpanId != nil {
		return *x.ParentSpanId
	}
	return ""
}

// 凭证句柄——只带名字与范围，不带值（第三章 §3.7）
type CredentialRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope         *string                `protobuf:"bytes,2,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRef) Reset() {
	*x = CredentialRef{}
	mi := &file_contract_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRef) ProtoMessage() {}

func (x *CredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRef.ProtoReflect.Descriptor instead.
func (*CredentialRef) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialRef) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

// 调用上下文（第三章 §3.2）——随每次调用透传
type CallContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Principal      *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Caller         *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Scene          string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"` // 三元组之 scene，如 agent.tool_call / frontend.api / runner.exec
	TenantId       string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId      *string                `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Trace          *Trace                 `protobuf:"bytes,6,opt,name=trace,proto3" json:"trace,omitempty"`
	DeadlineUnixMs *int64                 `protobuf:"varint,7,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3,oneof" json:"deadline_unix_ms,omitempty"`
	Credentials    []*CredentialRef       `protobuf:"bytes,8,rep,name=credentials,proto3" json:"credentials,omitempty"` // 句柄，非明文
	IdempotencyKey *string                `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallContext) Reset() {
	*x = CallContext{}
	mi := &file_contract_v1_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContext) ProtoMessage() {}

func (x *CallContext) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContext.ProtoReflect.Descriptor instead.
func (*CallContext) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *CallContext) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *CallContext) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *CallContext) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *CallContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CallContext) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *CallContext) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CallContext) GetDeadlineUnixMs() int64 {
	if x != nil && x.DeadlineUnixMs != nil {
		return *x.DeadlineUnixMs
	}
	return 0
}

func (x *CallContext) GetCredentials() []*CredentialRef {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *CallContext) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *CallContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 调用目标（第三章 §3.3）——调哪个扩展点·能力·操作
type CallTarget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtensionPoint string                 `protobuf:"bytes,1,opt,name=extension_point,json=extensionPoint,proto3" json:"extension_point,omitempty"` // 如 tool.package
	Capability     string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`                               // 贡献稳定逻辑名（= 清单 id），跨内核寻址亦用它
	Version        *string                `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Operation      *string                `protobuf:"bytes,4,opt,name=operation,proto3,oneof" json:"operation,omitempty"` // 子命令
	PayloadSchema  *string                `protobuf:"bytes,5,opt,name=payload_schema,json=payloadSchema,proto3,oneof" json:"payload_schema,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallTarget) Reset() {
	*x = CallTarget{}
	mi := &file_contract_v1_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTarget) ProtoMessage() {}

func (x *CallTarget) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTarget.ProtoReflect.Descriptor instead.
func (*CallTarget) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{6}
}

func (x *CallTarget) GetExtensionPoint() string {
	if x != nil {
		return x.ExtensionPoint
	}
	return ""
}

func (x *CallTarget) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CallTarget) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *CallTarget) GetOperation() string {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return ""
}

func (x *CallTarget) GetPayloadSchema() string {
	if x != nil && x.PayloadSchema != nil {
		return *x.PayloadSchema
	}
	return ""
}

// 错误（应用层，与传输层错误严格区分）
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 命名空间化，如 permission.denied
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_contract_v1_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// 计量
type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Tokens        *int64                 `protobuf:"varint,2,opt,name=tokens,proto3,oneof" json:"tokens,omitempty"`
	Cost          *float64               `protobuf:"fixed64,3,opt,name=cost,proto3,oneof" json:"cost,omitempty"`
	Custom        map[string]string      `protobuf:"bytes,4,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_contract_v1_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{8}
}

func (x *Usage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Usage) GetTokens() int64 {
	if x != nil && x.Tokens != nil {
		return *x.Tokens
	}
	return 0
}

func (x *Usage) GetCost() float64 {
	if x != nil && x.Cost != nil {
		return *x.Cost
	}
	return 0
}

func (x *Usage) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

// 调用结果（第三章 §3.4）
type CallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CallResult_Status      `protobuf:"varint,1,opt,name=status,proto3,enum=vastplan.contract.v1.CallResult_Status" json:"status,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3,oneof" json:"usage,omitempty"`
	Warnings      []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResult) Reset() {
	*x = CallResult{}
	mi := &file_contract_v1_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResult) ProtoMessage() {}

func (x *CallResult) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResult.ProtoReflect.Descriptor instead.
func (*CallResult) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{9}
}

func (x *CallResult) GetStatus() CallResult_Status {
	if x != nil {
		return x.Status
	}
	return CallResult_STATUS_UNSPECIFIED
}

func (x *CallResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CallResult) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CallResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CallResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 事件（第三章 §3.8）
type CallEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // 命名空间化，如 task.completed
	Source           string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // 服务/插件 id
	Subject          *string                `protobuf:"bytes,4,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	OccurredAtUnixMs int64                  `protobuf:"varint,5,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	TenantId         string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Trace            *Trace                 `protobuf:"bytes,7,opt,name=trace,proto3,oneof" json:"trace,omitempty"`
	PrincipalRef     *string                `protobuf:"bytes,8,opt,name=principal_ref,json=principalRef,proto3,oneof" json:"principal_ref,omitempty"`
	Payload          []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_contract_v1_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contract_v1_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_contract_v1_contract_proto_rawDescGZIP(), []int{10}
}

func (x *CallEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CallEvent) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *CallEvent) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

func (x *CallEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CallEvent) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CallEvent) GetPrincipalRef() string {
	if x != nil && x.PrincipalRef != nil {
		return *x.PrincipalRef
	}
	return ""
}

func (x *CallEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_contract_v1_contract_proto protoreflect.FileDescriptor

const file_contract_v1_contract_proto_rawDesc = "" +
	"\n" +
	"\x1acontract/v1/contract.proto\x12\x14vastplan.contract.v1\"\x87\x03\n" +
	"\tPrincipal\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12!\n" +
	"\fsystem_roles\x18\x05 \x03(\tR\vsystemRoles\x12V\n" +
	"\rproject_roles\x18\x06 \x03(\v21.vastplan.contract.v1.Principal.ProjectRolesEntryR\fprojectRoles\x12\"\n" +
	"\n" +
	"session_id\x18\a \x01(\tH\x00R\tsessionId\x88\x01\x01\x1a_\n" +
	"\x11ProjectRolesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.vastplan.contract.v1.RoleListR\x05value:\x028\x01B\r\n" +
	"\v_session_id\" \n" +
	"\bRoleList\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\"N\n" +
	"\x06Caller\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .vastplan.contract.v1.CallerKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"y\n" +
	"\x05Trace\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12)\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tH\x00R\fparentSpanId\x88\x01\x01B\x11\n" +
	"\x0f_parent_span_id\"H\n" +
	"\rCredentialRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05scope\x18\x02 \x01(\tH\x00R\x05scope\x88\x01\x01B\b\n" +
	"\x06_scope\"\xf2\x04\n" +
	"\vCallContext\x12=\n" +
	"\tprincipal\x18\x01 \x01(\v2\x1f.vastplan.contract.v1.PrincipalR\tprincipal\x124\n" +
	"\x06caller\x18\x02 \x01(\v2\x1c.vastplan.contract.v1.CallerR\x06caller\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\tR\x05scene\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\"\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tH\x00R\tprojectId\x88\x01\x01\x121\n" +
	"\x05trace\x18\x06 \x01(\v2\x1b.vastplan.contract.v1.TraceR\x05trace\x12-\n" +
	"\x10deadline_unix_ms\x18\a \x01(\x03H\x01R\x0edeadlineUnixMs\x88\x01\x01\x12E\n" +
	"\vcredentials\x18\b \x03(\v2#.vastplan.contract.v1.CredentialRefR\vcredentials\x12,\n" +
	"\x0fidempotency_key\x18\t \x01(\tH\x02R\x0eidempotencyKey\x88\x01\x01\x12K\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2/.vastplan.contract.v1.CallContext.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_project_idB\x13\n" +
	"\x11_deadline_unix_msB\x12\n" +
	"\x10_idempotency_key\"\xf0\x01\n" +
	"\n" +
	"CallTarget\x12'\n" +
	"\x0fextension_point\x18\x01 \x01(\tR\x0eextensionPoint\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x00R\aversion\x88\x01\x01\x12!\n" +
	"\toperation\x18\x04 \x01(\tH\x01R\toperation\x88\x01\x01\x12*\n" +
	"\x0epayload_schema\x18\x05 \x01(\tH\x02R\rpayloadSchema\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\f\n" +
	"\n" +
	"_operationB\x11\n" +
	"\x0f_payload_schema\"\xd3\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12B\n" +
	"\adetails\x18\x04 \x03(\v2(.vastplan.contract.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\x05Usage\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\x06tokens\x18\x02 \x01(\x03H\x00R\x06tokens\x88\x01\x01\x12\x17\n" +
	"\x04cost\x18\x03 \x01(\x01H\x01R\x04cost\x88\x01\x01\x12?\n" +
	"\x06custom\x18\x04 \x03(\v2'.vastplan.contract.v1.Usage.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_tokensB\a\n" +
	"\x05_cost\"\xcd\x03\n" +
	"\n" +
	"CallResult\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.vastplan.contract.v1.CallResult.StatusR\x06status\x126\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.vastplan.contract.v1.ErrorH\x00R\x05error\x88\x01\x01\x126\n" +
	"\x05usage\x18\x03 \x01(\v2\x1b.vastplan.contract.v1.UsageH\x01R\x05usage\x88\x01\x01\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..vastplan.contract.v1.CallResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PARTIAL\x10\x03B\b\n" +
	"\x06_errorB\b\n" +
	"\x06_usage\"\xd6\x02\n" +
	"\tCallEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\asubject\x18\x04 \x01(\tH\x00R\asubject\x88\x01\x01\x12-\n" +
	"\x13occurred_at_unix_ms\x18\x05 \x01(\x03R\x10occurredAtUnixMs\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x126\n" +
	"\x05trace\x18\a \x01(\v2\x1b.vastplan.contract.v1.TraceH\x01R\x05trace\x88\x01\x01\x12(\n" +
	"\rprincipal_ref\x18\b \x01(\tH\x02R\fprincipalRef\x88\x01\x01\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayloadB\n" +
	"\n" +
	"\b_subjectB\b\n" +
	"\x06_traceB\x10\n" +
	"\x0e_principal_ref*\x9e\x01\n" +
	"\n" +
	"CallerKind\x12\x1b\n" +
	"\x17CALLER_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CALLER_KIND_USER\x10\x01\x12\x15\n" +
	"\x11CALLER_KIND_AGENT\x10\x02\x12\x16\n" +
	"\x12CALLER_KIND_PLUGIN\x10\x03\x12\x16\n" +
	"\x12CALLER_KIND_SYSTEM\x10\x04\x12\x16\n" +
	"\x12CALLER_KIND_RUNNER\x10\x05B9Z7cdsoft.com.cn/VastPlan/shared/go/contract/v1;contractv1b\x06proto3"

var (
	file_contract_v1_contract_proto_rawDescOnce sync.Once
	file_contract_v1_contract_proto_rawDescData []byte
)

func file_contract_v1_contract_proto_rawDescGZIP() []byte {
	file_contract_v1_contract_proto_rawDescOnce.Do(func() {
		file_contract_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_v1_contract_proto_rawDesc), len(file_contract_v1_contract_proto_rawDesc)))
	})
	return file_contract_v1_contract_proto_rawDescData
}

var file_contract_v1_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contract_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_contract_v1_contract_proto_goTypes = []any{
	(CallerKind)(0),        // 0: vastplan.contract.v1.CallerKind
	(CallResult_Status)(0), // 1: vastplan.contract.v1.CallResult.Status
	(*Principal)(nil),      // 2: vastplan.contract.v1.Principal
	(*RoleList)(nil),       // 3: vastplan.contract.v1.RoleList
	(*Caller)(nil),         // 4: vastplan.contract.v1.Caller
	(*Trace)(nil),          // 5: vastplan.contract.v1.Trace
	(*CredentialRef)(nil),  // 6: vastplan.contract.v1.CredentialRef
	(*CallContext)(nil),    // 7: vastplan.contract.v1.CallContext
	(*CallTarget)(nil),     // 8: vastplan.contract.v1.CallTarget
	(*Error)(nil),          // 9: vastplan.contract.v1.Error
	(*Usage)(nil),          // 10: vastplan.contract.v1.Usage
	(*CallResult)(nil),     // 11: vastplan.contract.v1.CallResult
	(*CallEvent)(nil),      // 12: vastplan.contract.v1.CallEvent
	nil,                    // 13: vastplan.contract.v1.Principal.ProjectRolesEntry
	nil,                    // 14: vastplan.contract.v1.CallContext.MetadataEntry
	nil,                    // 15: vastplan.contract.v1.Error.DetailsEntry
	nil,                    // 16: vastplan.contract.v1.Usage.CustomEntry
	nil,                    // 17: vastplan.contract.v1.CallResult.MetadataEntry
}
var file_contract_v1_contract_proto_depIdxs = []int32{
	13, // 0: vastplan.contract.v1.Principal.project_roles:type_name -> vastplan.contract.v1.Principal.ProjectRolesEntry
	0,  // 1: vastplan.contract.v1.Caller.kind:type_name -> vastplan.contract.v1.CallerKind
	2,  // 2: vastplan.contract.v1.CallContext.principal:type_name -> vastplan.contract.v1.Principal
	4,  // 3: vastplan.contract.v1.CallContext.caller:type_name -> vastplan.contract.v1.Caller
	5,  // 4: vastplan.contract.v1.CallContext.trace:type_name -> vastplan.contract.v1.Trace
	6,  // 5: vastplan.contract.v1.CallContext.credentials:type_name -> vastplan.contract.v1.CredentialRef
	14, // 6: vastplan.contract.v1.CallContext.metadata:type_name -> vastplan.contract.v1.CallContext.MetadataEntry
	15, // 7: vastplan.contract.v1.Error.details:type_name -> vastplan.contract.v1.Error.DetailsEntry
	16, // 8: vastplan.contract.v1.Usage.custom:type_name -> vastplan.contract.v1.Usage.CustomEntry
	1,  // 9: vastplan.contract.v1.CallResult.status:type_name -> vastplan.contract.v1.CallResult.Status
	9,  // 10: vastplan.contract.v1.CallResult.error:type_name -> vastplan.contract.v1.Error
	10, // 11: vastplan.contract.v1.CallResult.usage:type_name -> vastplan.contract.v1.Usage
	17, // 12: vastplan.contract.v1.CallResult.metadata:type_name -> vastplan.contract.v1.CallResult.MetadataEntry
	5,  // 13: vastplan.contract.v1.CallEvent.trace:type_name -> vastplan.contract.v1.Trace
	3,  // 14: vastplan.contract.v1.Principal.ProjectRolesEntry.value:type_name -> vastplan.contract.v1.RoleList
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_contract_v1_contract_proto_init() }
func file_contract_v1_contract_proto_init() {
	if File_contract_v1_contract_proto != nil {
		return
	}
	file_contract_v1_contract_proto_msgTypes[0].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[3].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[4].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[5].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[6].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[8].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[9].OneofWrappers = []any{}
	file_contract_v1_contract_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_v1_contract_proto_rawDesc), len(file_contract_v1_contract_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_v1_contract_proto_goTypes,
		DependencyIndexes: file_contract_v1_contract_proto_depIdxs,
		EnumInfos:         file_contract_v1_contract_proto_enumTypes,
		MessageInfos:      file_contract_v1_contract_proto_msgTypes,
	}.Build()
	File_contract_v1_contract_proto = out.File
	file_contract_v1_contract_proto_goTypes = nil
	file_contract_v1_contract_proto_depIdxs = nil
}
