// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: addressing/v1/addressing.proto

// 后端服务间寻址 Wire v1。业务契约复用 contract.v1，本文件只定义远端传输信封。

package addressingv1

import (
	v1 "cdsoft.com.cn/VastPlan/shared/go/contract/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        *v1.CallTarget         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Context       *v1.CallContext        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeRequest) GetTarget() *v1.CallTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InvokeRequest) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result         *v1.CallResult         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TransportError *TransportError        `protobuf:"bytes,4,opt,name=transport_error,json=transportError,proto3,oneof" json:"transport_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeResponse) GetResult() *v1.CallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeResponse) GetTransportError() *TransportError {
	if x != nil {
		return x.TransportError
	}
	return nil
}

type TransportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportError) Reset() {
	*x = TransportError{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportError) ProtoMessage() {}

func (x *TransportError) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportError.ProtoReflect.Descriptor instead.
func (*TransportError) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{2}
}

func (x *TransportError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TransportError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransportError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.CallContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Event         *v1.CallEvent          `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{3}
}

func (x *EventEnvelope) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EventEnvelope) GetEvent() *v1.CallEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_addressing_v1_addressing_proto protoreflect.FileDescriptor

const file_addressing_v1_addressing_proto_rawDesc = "" +
	"\n" +
	"\x1eaddressing/v1/addressing.proto\x12\x16vastplan.addressing.v1\x1a\x1acontract/v1/contract.proto\"\xbf\x01\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06target\x18\x02 \x01(\v2 .vastplan.contract.v1.CallTargetR\x06target\x12;\n" +
	"\acontext\x18\x03 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xed\x01\n" +
	"\x0eInvokeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06result\x18\x02 \x01(\v2 .vastplan.contract.v1.CallResultR\x06result\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12T\n" +
	"\x0ftransport_error\x18\x04 \x01(\v2&.vastplan.addressing.v1.TransportErrorH\x00R\x0etransportError\x88\x01\x01B\x12\n" +
	"\x10_transport_error\"\\\n" +
	"\x0eTransportError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x83\x01\n" +
	"\rEventEnvelope\x12;\n" +
	"\acontext\x18\x01 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x125\n" +
	"\x05event\x18\x02 \x01(\v2\x1f.vastplan.contract.v1.CallEventR\x05eventB=Z;cdsoft.com.cn/VastPlan/shared/go/addressing/v1;addressingv1b\x06proto3"

var (
	file_addressing_v1_addressing_proto_rawDescOnce sync.Once
	file_addressing_v1_addressing_proto_rawDescData []byte
)

func file_addressing_v1_addressing_proto_rawDescGZIP() []byte {
	file_addressing_v1_addressing_proto_rawDescOnce.Do(func() {
		file_addressing_v1_addressing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addressing_v1_addressing_proto_rawDesc), len(file_addressing_v1_addressing_proto_rawDesc)))
	})
	return file_addressing_v1_addressing_proto_rawDescData
}

var file_addressing_v1_addressing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_addressing_v1_addressing_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: vastplan.addressing.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: vastplan.addressing.v1.InvokeResponse
	(*TransportError)(nil), // 2: vastplan.addressing.v1.TransportError
	(*EventEnvelope)(nil),  // 3: vastplan.addressing.v1.EventEnvelope
	(*v1.CallTarget)(nil),  // 4: vastplan.contract.v1.CallTarget
	(*v1.CallContext)(nil), // 5: vastplan.contract.v1.CallContext
	(*v1.CallResult)(nil),  // 6: vastplan.contract.v1.CallResult
	(*v1.CallEvent)(nil),   // 7: vastplan.contract.v1.CallEvent
}
var file_addressing_v1_addressing_proto_depIdxs = []int32{
	4, // 0: vastplan.addressing.v1.InvokeRequest.target:type_name -> vastplan.contract.v1.CallTarget
	5, // 1: vastplan.addressing.v1.InvokeRequest.context:type_name -> vastplan.contract.v1.CallContext
	6, // 2: vastplan.addressing.v1.InvokeResponse.result:type_name -> vastplan.contract.v1.CallResult
	2, // 3: vastplan.addressing.v1.InvokeResponse.transport_error:type_name -> vastplan.addressing.v1.TransportError
	5, // 4: vastplan.addressing.v1.EventEnvelope.context:type_name -> vastplan.contract.v1.CallContext
	7, // 5: vastplan.addressing.v1.EventEnvelope.event:type_name -> vastplan.contract.v1.CallEvent
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_addressing_v1_addressing_proto_init() }
func file_addressing_v1_addressing_proto_init() {
	if File_addressing_v1_addressing_proto != nil {
		return
	}
	file_addressing_v1_addressing_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addressing_v1_addressing_proto_rawDesc), len(file_addressing_v1_addressing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_addressing_v1_addressing_proto_goTypes,
		DependencyIndexes: file_addressing_v1_addressing_proto_depIdxs,
		MessageInfos:      file_addressing_v1_addressing_proto_msgTypes,
	}.Build()
	File_addressing_v1_addressing_proto = out.File
	file_addressing_v1_addressing_proto_goTypes = nil
	file_addressing_v1_addressing_proto_depIdxs = nil
}
