// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: addressing/v1/addressing.proto

// 后端服务间寻址 Wire v1。业务契约复用 contract.v1，本文件只定义远端传输信封。

package addressingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityStream_Open_FullMethodName = "/vastplan.addressing.v1.CapabilityStream/Open"
)

// CapabilityStreamClient is the client API for CapabilityStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapabilityStream 承载跨服务的大输入、大输出和交互式调用。
// HTTP/2 流控提供背压；任一端取消 RPC 会立刻传播到对端 context。
type CapabilityStreamClient interface {
	Open(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error)
}

type capabilityStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityStreamClient(cc grpc.ClientConnInterface) CapabilityStreamClient {
	return &capabilityStreamClient{cc}
}

func (c *capabilityStreamClient) Open(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CapabilityStream_ServiceDesc.Streams[0], CapabilityStream_Open_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFrame, StreamFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapabilityStream_OpenClient = grpc.BidiStreamingClient[StreamFrame, StreamFrame]

// CapabilityStreamServer is the server API for CapabilityStream service.
// All implementations must embed UnimplementedCapabilityStreamServer
// for forward compatibility.
//
// CapabilityStream 承载跨服务的大输入、大输出和交互式调用。
// HTTP/2 流控提供背压；任一端取消 RPC 会立刻传播到对端 context。
type CapabilityStreamServer interface {
	Open(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error
	mustEmbedUnimplementedCapabilityStreamServer()
}

// UnimplementedCapabilityStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityStreamServer struct{}

func (UnimplementedCapabilityStreamServer) Open(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error {
	return status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedCapabilityStreamServer) mustEmbedUnimplementedCapabilityStreamServer() {}
func (UnimplementedCapabilityStreamServer) testEmbeddedByValue()                          {}

// UnsafeCapabilityStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityStreamServer will
// result in compilation errors.
type UnsafeCapabilityStreamServer interface {
	mustEmbedUnimplementedCapabilityStreamServer()
}

func RegisterCapabilityStreamServer(s grpc.ServiceRegistrar, srv CapabilityStreamServer) {
	// If the following call panics, it indicates UnimplementedCapabilityStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityStream_ServiceDesc, srv)
}

func _CapabilityStream_Open_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CapabilityStreamServer).Open(&grpc.GenericServerStream[StreamFrame, StreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapabilityStream_OpenServer = grpc.BidiStreamingServer[StreamFrame, StreamFrame]

// CapabilityStream_ServiceDesc is the grpc.ServiceDesc for CapabilityStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vastplan.addressing.v1.CapabilityStream",
	HandlerType: (*CapabilityStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Open",
			Handler:       _CapabilityStream_Open_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "addressing/v1/addressing.proto",
}
