// Package apiv1 defines governed public API exposure contracts. Public route
// identity is deliberately independent from plugin and capability identity.
package apiv1

import (
	"encoding/json"
	"time"
)

const (
	SchemaURL        = "https://schemas.cdsoft.com.cn/vastplan/api/v1/vastplan.api-exposure.schema.json"
	SchemaVersion    = "v1"
	ProtocolHTTPJSON = "http-json"

	ModeGatewayProxy   = "gateway-proxy"
	ModeTicketRedirect = "ticket-redirect"
	ModePrivateDirect  = "private-direct"
)

// ContractContribution is immutable signed package metadata. ID is only
// package-local and is never used as a public URL segment.
type ContractContribution struct {
	ID              string          `json:"id"`
	ServiceRole     string          `json:"service_role"`
	Title           string          `json:"title,omitempty"`
	ContractID      string          `json:"contractId"`
	ContractVersion string          `json:"contractVersion"`
	Protocol        string          `json:"protocol"`
	Routes          []RouteContract `json:"routes"`
}

type RouteContract struct {
	ID             string           `json:"id"`
	Method         string           `json:"method"`
	Path           string           `json:"path"`
	Target         CapabilityTarget `json:"target"`
	RequestSchema  json.RawMessage  `json:"requestSchema"`
	ResponseSchema json.RawMessage  `json:"responseSchema"`
	SuccessStatus  int              `json:"successStatus"`
	Errors         []ErrorMapping   `json:"errors,omitempty"`
}

type CapabilityTarget struct {
	Capability string `json:"capability"`
	Operation  string `json:"operation"`
}

type ErrorMapping struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

// DataPlaneServiceContribution describes an independently listening service.
// Its runtime endpoint is never package metadata and is supplied only by a
// short-lived trusted-host lease.
type DataPlaneServiceContribution struct {
	ID             string            `json:"id"`
	ServiceRole    string            `json:"service_role"`
	Title          string            `json:"title,omitempty"`
	Protocol       string            `json:"protocol"`
	Purposes       []string          `json:"purposes"`
	SupportedModes []string          `json:"supportedModes"`
	HealthPath     string            `json:"healthPath"`
	MaxObjectBytes uint64            `json:"maxObjectBytes"`
	TicketTarget   *CapabilityTarget `json:"ticketTarget,omitempty"`
}

type ContractReference struct {
	PluginID        string `json:"pluginId"`
	ArtifactSHA256  string `json:"artifactSha256"`
	ContributionID  string `json:"contributionId"`
	ContractID      string `json:"contractId"`
	ContractVersion string `json:"contractVersion"`
	ContractDigest  string `json:"contractDigest"`
}

type ResolvedContract struct {
	Reference ContractReference    `json:"reference"`
	Contract  ContractContribution `json:"contract"`
}

type DataPlaneServiceReference struct {
	PluginID       string `json:"pluginId"`
	ArtifactSHA256 string `json:"artifactSha256"`
	ContributionID string `json:"contributionId"`
}

type ResolvedDataPlaneService struct {
	Reference DataPlaneServiceReference    `json:"reference"`
	Service   DataPlaneServiceContribution `json:"service"`
}

// ContractCatalog 只能由可信宿主从已验签制品生成；管理插件不得接受浏览器
// 自行拼装的 ContractContribution 作为发布依据。
type ContractCatalog struct {
	SchemaVersion     string                     `json:"schemaVersion"`
	Generation        uint64                     `json:"generation"`
	Contracts         []ResolvedContract         `json:"contracts"`
	DataPlaneServices []ResolvedDataPlaneService `json:"dataPlaneServices"`
}

type ExposureTarget struct {
	LogicalService string `json:"logicalService"`
	RoutingDomain  string `json:"routingDomain"`
}

type AuthenticationPolicy struct {
	ProfileID      string `json:"profileId"`
	AllowAnonymous bool   `json:"allowAnonymous"`
}

type ExposureLimits struct {
	MaxBodyBytes      uint64 `json:"maxBodyBytes"`
	MaxResponseBytes  uint64 `json:"maxResponseBytes"`
	RequestsPerMinute uint64 `json:"requestsPerMinute"`
	TimeoutMS         uint64 `json:"timeoutMs"`
}

// Exposure is the immutable current public binding. RouteKey is generated by
// the platform and remains stable when the implementation plugin changes.
type Exposure struct {
	SchemaVersion       string               `json:"schemaVersion"`
	ID                  string               `json:"id"`
	Revision            uint64               `json:"revision"`
	RouteKey            string               `json:"routeKey"`
	DisplayName         string               `json:"displayName"`
	TenantID            string               `json:"tenantId"`
	PortalID            string               `json:"portalId,omitempty"`
	Hosts               []string             `json:"hosts"`
	Contract            ContractReference    `json:"contract"`
	Authentication      AuthenticationPolicy `json:"authentication"`
	RequiredPermissions []string             `json:"requiredPermissions"`
	Limits              ExposureLimits       `json:"limits"`
	Target              ExposureTarget       `json:"target"`
}

// ResolvedExposure 是投递给 Gateway 的自包含、不可变快照。Gateway 不回查插件
// 清单，也不根据插件 ID 生成或解析公开地址。
type ResolvedExposure struct {
	Exposure Exposure             `json:"exposure"`
	Contract ContractContribution `json:"contract"`
}

type ExposureCatalog struct {
	SchemaVersion      string              `json:"schemaVersion"`
	Generation         uint64              `json:"generation"`
	Exposures          []ResolvedExposure  `json:"exposures"`
	DataPlaneExposures []DataPlaneExposure `json:"dataPlaneExposures"`
}

type DataPlaneExposure struct {
	SchemaVersion          string                    `json:"schemaVersion"`
	ID                     string                    `json:"id"`
	Revision               uint64                    `json:"revision"`
	RouteKey               string                    `json:"routeKey"`
	TenantID               string                    `json:"tenantId"`
	Hosts                  []string                  `json:"hosts"`
	Service                DataPlaneServiceReference `json:"service"`
	DataPlaneServiceID     string                    `json:"dataPlaneServiceId"`
	AllowedModes           []string                  `json:"allowedModes"`
	AllowedEndpointOrigins []string                  `json:"allowedEndpointOrigins"`
	TLSIdentityPrefix      string                    `json:"tlsIdentityPrefix"`
	Authentication         AuthenticationPolicy      `json:"authentication"`
	RequiredPermissions    []string                  `json:"requiredPermissions"`
	MaxObjectBytes         uint64                    `json:"maxObjectBytes"`
}

type EndpointLease struct {
	SchemaVersion       string    `json:"schemaVersion"`
	LeaseID             string    `json:"leaseId"`
	DataPlaneExposureID string    `json:"dataPlaneExposureId"`
	InstanceID          string    `json:"instanceId"`
	Endpoint            string    `json:"endpoint"`
	TLSIdentity         string    `json:"tlsIdentity"`
	Modes               []string  `json:"modes"`
	IssuedAt            time.Time `json:"issuedAt"`
	ExpiresAt           time.Time `json:"expiresAt"`
}

type EndpointLeaseRegistration struct {
	DataPlaneExposureID string   `json:"dataPlaneExposureId"`
	InstanceID          string   `json:"instanceId"`
	Endpoint            string   `json:"endpoint"`
	TLSIdentity         string   `json:"tlsIdentity"`
	Modes               []string `json:"modes"`
	TTLSeconds          uint64   `json:"ttlSeconds"`
}

type EndpointLeaseRenewal struct {
	LeaseID    string `json:"leaseId"`
	TTLSeconds uint64 `json:"ttlSeconds"`
}

type EndpointLeaseRevocation struct {
	LeaseID string `json:"leaseId"`
}

type DataPlaneTicketClaims struct {
	TenantID            string    `json:"tenantId"`
	PrincipalID         string    `json:"principalId"`
	DataPlaneExposureID string    `json:"dataPlaneExposureId"`
	InstanceID          string    `json:"instanceId"`
	Method              string    `json:"method"`
	Resource            string    `json:"resource"`
	ContentSHA256       string    `json:"contentSha256,omitempty"`
	ExpiresAt           time.Time `json:"expiresAt"`
}

type DataPlaneTicketInstallation struct {
	Ticket string                `json:"ticket"`
	Claims DataPlaneTicketClaims `json:"claims"`
}

// GatewayInvocation is the bounded language-neutral request passed to a route
// target. Authentication, tenant and trace remain in trusted CallContext.
type GatewayInvocation struct {
	SchemaVersion string              `json:"schemaVersion"`
	RouteID       string              `json:"routeId"`
	Method        string              `json:"method"`
	PathParams    map[string]string   `json:"pathParams"`
	Query         map[string][]string `json:"query"`
	Body          json.RawMessage     `json:"body"`
}
