// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.

package portalcomposer

const (
	PluginID      = "cn.vastplan.platform.configuration.portal-composer"
	PluginVersion = "2.0.1"
)

var signedToolDescriptors = map[string]string{
	"platform.portal-composer":   "{\"subcommands\":[{\"audience\":\"user\",\"description\":\"读取 Portal 聚合及其版本和上线历史\",\"name\":\"portalGovernance\"},{\"audience\":\"user\",\"description\":\"读取运行时需要的 Portal 上线记录\",\"name\":\"listPortalReleases\"},{\"audience\":\"user\",\"description\":\"创建 Portal 及首个完整配置版本\",\"name\":\"createPortal\"},{\"audience\":\"user\",\"description\":\"在 Portal 内创建完整配置版本\",\"name\":\"createPortalVersion\"},{\"audience\":\"user\",\"description\":\"更新 Portal 完整配置草稿\",\"name\":\"updatePortalVersion\"},{\"audience\":\"user\",\"description\":\"删除未提交的 Portal 版本\",\"name\":\"deletePortalVersion\"},{\"audience\":\"user\",\"description\":\"提交 Portal 版本审批\",\"name\":\"submitPortalVersion\"},{\"audience\":\"user\",\"description\":\"审批 Portal 版本\",\"name\":\"approvePortalVersion\"},{\"audience\":\"user\",\"description\":\"发布不可变 Portal 版本\",\"name\":\"publishPortalVersion\"},{\"audience\":\"user\",\"description\":\"将已发布 Portal 版本上线\",\"name\":\"releasePortalVersion\"},{\"audience\":\"user\",\"description\":\"从历史版本创建新的 Portal 上线记录\",\"name\":\"rollbackPortalRelease\"},{\"audience\":\"user\",\"description\":\"列出 Frontend 测试目标绑定\",\"name\":\"listTestTargetBindings\"},{\"audience\":\"user\",\"description\":\"CAS 保存 Frontend 应用插件测试目标\",\"name\":\"putTestTargetBinding\"},{\"audience\":\"user\",\"description\":\"列出 Frontend Test Release\",\"name\":\"listTestReleases\"},{\"audience\":\"user\",\"description\":\"提交精确 Frontend 测试制品\",\"name\":\"createTestRelease\"},{\"audience\":\"user\",\"description\":\"恢复中断的 Frontend Test Release\",\"name\":\"rollbackTestRelease\"},{\"audience\":\"user\",\"description\":\"读取 revision 审计\",\"name\":\"audit\"}],\"title\":\"门户组合治理\"}",
	"platform.portal-preference": "{\"subcommands\":[{\"description\":\"读取当前主体的 Portal 偏好\",\"name\":\"get\"},{\"description\":\"以 CAS 保存当前主体的 Portal 偏好\",\"name\":\"put\"}],\"title\":\"Portal 用户偏好\"}",
}

var signedToolOperations = map[string][]string{
	"platform.portal-composer":   {"portalGovernance", "listPortalReleases", "createPortal", "createPortalVersion", "updatePortalVersion", "deletePortalVersion", "submitPortalVersion", "approvePortalVersion", "publishPortalVersion", "releasePortalVersion", "rollbackPortalRelease", "listTestTargetBindings", "putTestTargetBinding", "listTestReleases", "createTestRelease", "rollbackTestRelease", "audit"},
	"platform.portal-preference": {"get", "put"},
}

func signedToolDescriptor(capability string) []byte {
	raw, ok := signedToolDescriptors[capability]
	if !ok {
		panic("未生成签名 Tool Capability Contract: " + capability)
	}
	return []byte(raw)
}

func signedToolOperationNames(capability string) []string {
	operations, ok := signedToolOperations[capability]
	if !ok {
		panic("未生成签名 Tool operations: " + capability)
	}
	return append([]string(nil), operations...)
}
