// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: addressing/v1/addressing.proto

// 后端服务间寻址 Wire v1。业务契约复用 contract.v1，本文件只定义远端传输信封。

package addressingv1

import (
	v1 "cdsoft.com.cn/VastPlan/core/shared/go/contract/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        *v1.CallTarget         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Context       *v1.CallContext        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeRequest) GetTarget() *v1.CallTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InvokeRequest) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result         *v1.CallResult         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TransportError *TransportError        `protobuf:"bytes,4,opt,name=transport_error,json=transportError,proto3,oneof" json:"transport_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeResponse) GetResult() *v1.CallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeResponse) GetTransportError() *TransportError {
	if x != nil {
		return x.TransportError
	}
	return nil
}

type TransportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportError) Reset() {
	*x = TransportError{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportError) ProtoMessage() {}

func (x *TransportError) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportError.ProtoReflect.Descriptor instead.
func (*TransportError) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{2}
}

func (x *TransportError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TransportError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransportError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.CallContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Event         *v1.CallEvent          `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{3}
}

func (x *EventEnvelope) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EventEnvelope) GetEvent() *v1.CallEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type StreamOpen struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Target         *v1.CallTarget         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Context        *v1.CallContext        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	InitialPayload []byte                 `protobuf:"bytes,3,opt,name=initial_payload,json=initialPayload,proto3" json:"initial_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOpen) Reset() {
	*x = StreamOpen{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpen) ProtoMessage() {}

func (x *StreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpen.ProtoReflect.Descriptor instead.
func (*StreamOpen) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{4}
}

func (x *StreamOpen) GetTarget() *v1.CallTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamOpen) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StreamOpen) GetInitialPayload() []byte {
	if x != nil {
		return x.InitialPayload
	}
	return nil
}

type StreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPayload) Reset() {
	*x = StreamPayload{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPayload) ProtoMessage() {}

func (x *StreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPayload.ProtoReflect.Descriptor instead.
func (*StreamPayload) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{5}
}

func (x *StreamPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnd) Reset() {
	*x = StreamEnd{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnd) ProtoMessage() {}

func (x *StreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnd.ProtoReflect.Descriptor instead.
func (*StreamEnd) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{6}
}

type StreamCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCancel) Reset() {
	*x = StreamCancel{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCancel) ProtoMessage() {}

func (x *StreamCancel) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCancel.ProtoReflect.Descriptor instead.
func (*StreamCancel) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{7}
}

func (x *StreamCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StreamResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         *v1.CallResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TransportError *TransportError        `protobuf:"bytes,3,opt,name=transport_error,json=transportError,proto3,oneof" json:"transport_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{8}
}

func (x *StreamResult) GetResult() *v1.CallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StreamResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamResult) GetTransportError() *TransportError {
	if x != nil {
		return x.TransportError
	}
	return nil
}

type StreamFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*StreamFrame_Open
	//	*StreamFrame_Payload
	//	*StreamFrame_End
	//	*StreamFrame_Cancel
	//	*StreamFrame_Result
	Body          isStreamFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_addressing_v1_addressing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_addressing_v1_addressing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_addressing_v1_addressing_proto_rawDescGZIP(), []int{9}
}

func (x *StreamFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamFrame) GetBody() isStreamFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamFrame) GetOpen() *StreamOpen {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *StreamFrame) GetPayload() *StreamPayload {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *StreamFrame) GetEnd() *StreamEnd {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *StreamFrame) GetCancel() *StreamCancel {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *StreamFrame) GetResult() *StreamResult {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isStreamFrame_Body interface {
	isStreamFrame_Body()
}

type StreamFrame_Open struct {
	Open *StreamOpen `protobuf:"bytes,3,opt,name=open,proto3,oneof"`
}

type StreamFrame_Payload struct {
	Payload *StreamPayload `protobuf:"bytes,4,opt,name=payload,proto3,oneof"`
}

type StreamFrame_End struct {
	End *StreamEnd `protobuf:"bytes,5,opt,name=end,proto3,oneof"`
}

type StreamFrame_Cancel struct {
	Cancel *StreamCancel `protobuf:"bytes,6,opt,name=cancel,proto3,oneof"`
}

type StreamFrame_Result struct {
	Result *StreamResult `protobuf:"bytes,7,opt,name=result,proto3,oneof"`
}

func (*StreamFrame_Open) isStreamFrame_Body() {}

func (*StreamFrame_Payload) isStreamFrame_Body() {}

func (*StreamFrame_End) isStreamFrame_Body() {}

func (*StreamFrame_Cancel) isStreamFrame_Body() {}

func (*StreamFrame_Result) isStreamFrame_Body() {}

var File_addressing_v1_addressing_proto protoreflect.FileDescriptor

const file_addressing_v1_addressing_proto_rawDesc = "" +
	"\n" +
	"\x1eaddressing/v1/addressing.proto\x12\x16vastplan.addressing.v1\x1a\x1acontract/v1/contract.proto\"\xbf\x01\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06target\x18\x02 \x01(\v2 .vastplan.contract.v1.CallTargetR\x06target\x12;\n" +
	"\acontext\x18\x03 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xed\x01\n" +
	"\x0eInvokeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06result\x18\x02 \x01(\v2 .vastplan.contract.v1.CallResultR\x06result\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12T\n" +
	"\x0ftransport_error\x18\x04 \x01(\v2&.vastplan.addressing.v1.TransportErrorH\x00R\x0etransportError\x88\x01\x01B\x12\n" +
	"\x10_transport_error\"\\\n" +
	"\x0eTransportError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x83\x01\n" +
	"\rEventEnvelope\x12;\n" +
	"\acontext\x18\x01 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x125\n" +
	"\x05event\x18\x02 \x01(\v2\x1f.vastplan.contract.v1.CallEventR\x05event\"\xac\x01\n" +
	"\n" +
	"StreamOpen\x128\n" +
	"\x06target\x18\x01 \x01(\v2 .vastplan.contract.v1.CallTargetR\x06target\x12;\n" +
	"\acontext\x18\x02 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x12'\n" +
	"\x0finitial_payload\x18\x03 \x01(\fR\x0einitialPayload\"#\n" +
	"\rStreamPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\v\n" +
	"\tStreamEnd\"&\n" +
	"\fStreamCancel\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xcc\x01\n" +
	"\fStreamResult\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .vastplan.contract.v1.CallResultR\x06result\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12T\n" +
	"\x0ftransport_error\x18\x03 \x01(\v2&.vastplan.addressing.v1.TransportErrorH\x00R\x0etransportError\x88\x01\x01B\x12\n" +
	"\x10_transport_error\"\x84\x03\n" +
	"\vStreamFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x128\n" +
	"\x04open\x18\x03 \x01(\v2\".vastplan.addressing.v1.StreamOpenH\x00R\x04open\x12A\n" +
	"\apayload\x18\x04 \x01(\v2%.vastplan.addressing.v1.StreamPayloadH\x00R\apayload\x125\n" +
	"\x03end\x18\x05 \x01(\v2!.vastplan.addressing.v1.StreamEndH\x00R\x03end\x12>\n" +
	"\x06cancel\x18\x06 \x01(\v2$.vastplan.addressing.v1.StreamCancelH\x00R\x06cancel\x12>\n" +
	"\x06result\x18\a \x01(\v2$.vastplan.addressing.v1.StreamResultH\x00R\x06resultB\x06\n" +
	"\x04body2h\n" +
	"\x10CapabilityStream\x12T\n" +
	"\x04Open\x12#.vastplan.addressing.v1.StreamFrame\x1a#.vastplan.addressing.v1.StreamFrame(\x010\x01BBZ@cdsoft.com.cn/VastPlan/core/shared/go/addressing/v1;addressingv1b\x06proto3"

var (
	file_addressing_v1_addressing_proto_rawDescOnce sync.Once
	file_addressing_v1_addressing_proto_rawDescData []byte
)

func file_addressing_v1_addressing_proto_rawDescGZIP() []byte {
	file_addressing_v1_addressing_proto_rawDescOnce.Do(func() {
		file_addressing_v1_addressing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addressing_v1_addressing_proto_rawDesc), len(file_addressing_v1_addressing_proto_rawDesc)))
	})
	return file_addressing_v1_addressing_proto_rawDescData
}

var file_addressing_v1_addressing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_addressing_v1_addressing_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: vastplan.addressing.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: vastplan.addressing.v1.InvokeResponse
	(*TransportError)(nil), // 2: vastplan.addressing.v1.TransportError
	(*EventEnvelope)(nil),  // 3: vastplan.addressing.v1.EventEnvelope
	(*StreamOpen)(nil),     // 4: vastplan.addressing.v1.StreamOpen
	(*StreamPayload)(nil),  // 5: vastplan.addressing.v1.StreamPayload
	(*StreamEnd)(nil),      // 6: vastplan.addressing.v1.StreamEnd
	(*StreamCancel)(nil),   // 7: vastplan.addressing.v1.StreamCancel
	(*StreamResult)(nil),   // 8: vastplan.addressing.v1.StreamResult
	(*StreamFrame)(nil),    // 9: vastplan.addressing.v1.StreamFrame
	(*v1.CallTarget)(nil),  // 10: vastplan.contract.v1.CallTarget
	(*v1.CallContext)(nil), // 11: vastplan.contract.v1.CallContext
	(*v1.CallResult)(nil),  // 12: vastplan.contract.v1.CallResult
	(*v1.CallEvent)(nil),   // 13: vastplan.contract.v1.CallEvent
}
var file_addressing_v1_addressing_proto_depIdxs = []int32{
	10, // 0: vastplan.addressing.v1.InvokeRequest.target:type_name -> vastplan.contract.v1.CallTarget
	11, // 1: vastplan.addressing.v1.InvokeRequest.context:type_name -> vastplan.contract.v1.CallContext
	12, // 2: vastplan.addressing.v1.InvokeResponse.result:type_name -> vastplan.contract.v1.CallResult
	2,  // 3: vastplan.addressing.v1.InvokeResponse.transport_error:type_name -> vastplan.addressing.v1.TransportError
	11, // 4: vastplan.addressing.v1.EventEnvelope.context:type_name -> vastplan.contract.v1.CallContext
	13, // 5: vastplan.addressing.v1.EventEnvelope.event:type_name -> vastplan.contract.v1.CallEvent
	10, // 6: vastplan.addressing.v1.StreamOpen.target:type_name -> vastplan.contract.v1.CallTarget
	11, // 7: vastplan.addressing.v1.StreamOpen.context:type_name -> vastplan.contract.v1.CallContext
	12, // 8: vastplan.addressing.v1.StreamResult.result:type_name -> vastplan.contract.v1.CallResult
	2,  // 9: vastplan.addressing.v1.StreamResult.transport_error:type_name -> vastplan.addressing.v1.TransportError
	4,  // 10: vastplan.addressing.v1.StreamFrame.open:type_name -> vastplan.addressing.v1.StreamOpen
	5,  // 11: vastplan.addressing.v1.StreamFrame.payload:type_name -> vastplan.addressing.v1.StreamPayload
	6,  // 12: vastplan.addressing.v1.StreamFrame.end:type_name -> vastplan.addressing.v1.StreamEnd
	7,  // 13: vastplan.addressing.v1.StreamFrame.cancel:type_name -> vastplan.addressing.v1.StreamCancel
	8,  // 14: vastplan.addressing.v1.StreamFrame.result:type_name -> vastplan.addressing.v1.StreamResult
	9,  // 15: vastplan.addressing.v1.CapabilityStream.Open:input_type -> vastplan.addressing.v1.StreamFrame
	9,  // 16: vastplan.addressing.v1.CapabilityStream.Open:output_type -> vastplan.addressing.v1.StreamFrame
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_addressing_v1_addressing_proto_init() }
func file_addressing_v1_addressing_proto_init() {
	if File_addressing_v1_addressing_proto != nil {
		return
	}
	file_addressing_v1_addressing_proto_msgTypes[1].OneofWrappers = []any{}
	file_addressing_v1_addressing_proto_msgTypes[8].OneofWrappers = []any{}
	file_addressing_v1_addressing_proto_msgTypes[9].OneofWrappers = []any{
		(*StreamFrame_Open)(nil),
		(*StreamFrame_Payload)(nil),
		(*StreamFrame_End)(nil),
		(*StreamFrame_Cancel)(nil),
		(*StreamFrame_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addressing_v1_addressing_proto_rawDesc), len(file_addressing_v1_addressing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addressing_v1_addressing_proto_goTypes,
		DependencyIndexes: file_addressing_v1_addressing_proto_depIdxs,
		MessageInfos:      file_addressing_v1_addressing_proto_msgTypes,
	}.Build()
	File_addressing_v1_addressing_proto = out.File
	file_addressing_v1_addressing_proto_goTypes = nil
	file_addressing_v1_addressing_proto_depIdxs = nil
}
