// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.
export const portalComposerOperations = Object.freeze([
  "preparePluginInstallation",
  "commitPluginInstallation",
  "abortPluginInstallation",
  "rollbackPluginInstallation",
  "readNavigationConfiguration",
  "prepareNavigationConfiguration",
  "commitNavigationConfiguration",
  "abortNavigationConfiguration",
  "rollbackNavigationConfiguration",
  "portalGovernance",
  "listPortalReleases",
  "createPortal",
  "createPortalWorkingCopy",
  "savePortalWorkingCopy",
  "submitPortalPublication",
  "approvePortalPublication",
  "publishPortalPublication",
  "releasePortalPublication",
  "portalVersionHistory",
  "readPortalVersion",
  "comparePortalVersions",
  "restorePortalVersion",
  "rollbackPortalRelease",
  "listTestTargetBindings",
  "putTestTargetBinding",
  "listTestReleases",
  "createTestRelease",
  "rollbackTestRelease",
  "audit",
] as const);

export type PortalComposerOperation = (typeof portalComposerOperations)[number];

export const portalComposerOperationSet: ReadonlySet<string> = new Set(portalComposerOperations);
