// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.
export const portalComposerOperations = Object.freeze([
  "portalGovernance",
  "listPortalReleases",
  "createPortal",
  "createPortalVersion",
  "updatePortalVersion",
  "deletePortalVersion",
  "submitPortalVersion",
  "approvePortalVersion",
  "publishPortalVersion",
  "releasePortalVersion",
  "rollbackPortalRelease",
  "listTestTargetBindings",
  "putTestTargetBinding",
  "listTestReleases",
  "createTestRelease",
  "rollbackTestRelease",
  "audit",
] as const);

export type PortalComposerOperation = (typeof portalComposerOperations)[number];

export const portalComposerOperationSet: ReadonlySet<string> = new Set(portalComposerOperations);
