// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.
export const portalComposerOperations = Object.freeze([
  "governance",
  "createDraft",
  "updateDraft",
  "list",
  "submit",
  "approve",
  "publish",
  "createProfileDraft",
  "updateProfileDraft",
  "deleteProfileDraft",
  "submitProfile",
  "approveProfile",
  "publishProfile",
  "createBindingDraft",
  "updateBindingDraft",
  "submitBinding",
  "approveBinding",
  "publishBinding",
  "activate",
  "rollbackActivation",
  "listActivations",
  "listTestTargetBindings",
  "putTestTargetBinding",
  "listTestReleases",
  "createTestRelease",
  "rollbackTestRelease",
  "audit",
] as const);

export type PortalComposerOperation = (typeof portalComposerOperations)[number];

export const portalComposerOperationSet: ReadonlySet<string> = new Set(portalComposerOperations);
