// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: pluginhost/v1/pluginhost.proto

// 插件-宿主协议（Plugin-Host Protocol）——内核内：宿主 ↔ 本内核插件
// 规格见 docs/dev/architecture/插件契约与协议.md 第二章
//
// 方向：**宿主是 gRPC 服务端，插件是客户端**。宿主拉起插件时注入连接端点，
// 插件回连并主动 Hello（第二章 §2.2）。这样插件→宿主的回调是天然的，
// 宿主→插件的调用则经 Channel 双向流下发。

package pluginhostv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginHost_Handshake_FullMethodName = "/vastplan.pluginhost.v1.PluginHost/Handshake"
	PluginHost_Channel_FullMethodName   = "/vastplan.pluginhost.v1.PluginHost/Channel"
)

// PluginHostClient is the client API for PluginHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginHostClient interface {
	// 握手：校验 magic、协商版本、校验 engines、签发会话票据。
	Handshake(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloAck, error)
	// 运行态双向流：调用/事件/生命周期/心跳多路复用。
	// 插件须在 metadata 中携带 session_id（键见 shared/go/protocol）。
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromPlugin, FromHost], error)
}

type pluginHostClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHostClient(cc grpc.ClientConnInterface) PluginHostClient {
	return &pluginHostClient{cc}
}

func (c *pluginHostClient) Handshake(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloAck)
	err := c.cc.Invoke(ctx, PluginHost_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromPlugin, FromHost], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginHost_ServiceDesc.Streams[0], PluginHost_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromPlugin, FromHost]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginHost_ChannelClient = grpc.BidiStreamingClient[FromPlugin, FromHost]

// PluginHostServer is the server API for PluginHost service.
// All implementations must embed UnimplementedPluginHostServer
// for forward compatibility.
type PluginHostServer interface {
	// 握手：校验 magic、协商版本、校验 engines、签发会话票据。
	Handshake(context.Context, *Hello) (*HelloAck, error)
	// 运行态双向流：调用/事件/生命周期/心跳多路复用。
	// 插件须在 metadata 中携带 session_id（键见 shared/go/protocol）。
	Channel(grpc.BidiStreamingServer[FromPlugin, FromHost]) error
	mustEmbedUnimplementedPluginHostServer()
}

// UnimplementedPluginHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHostServer struct{}

func (UnimplementedPluginHostServer) Handshake(context.Context, *Hello) (*HelloAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginHostServer) Channel(grpc.BidiStreamingServer[FromPlugin, FromHost]) error {
	return status.Error(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedPluginHostServer) mustEmbedUnimplementedPluginHostServer() {}
func (UnimplementedPluginHostServer) testEmbeddedByValue()                    {}

// UnsafePluginHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHostServer will
// result in compilation errors.
type UnsafePluginHostServer interface {
	mustEmbedUnimplementedPluginHostServer()
}

func RegisterPluginHostServer(s grpc.ServiceRegistrar, srv PluginHostServer) {
	// If the following call panics, it indicates UnimplementedPluginHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHost_ServiceDesc, srv)
}

func _PluginHost_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Handshake(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginHostServer).Channel(&grpc.GenericServerStream[FromPlugin, FromHost]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginHost_ChannelServer = grpc.BidiStreamingServer[FromPlugin, FromHost]

// PluginHost_ServiceDesc is the grpc.ServiceDesc for PluginHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vastplan.pluginhost.v1.PluginHost",
	HandlerType: (*PluginHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PluginHost_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _PluginHost_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pluginhost/v1/pluginhost.proto",
}
