// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pluginhost/v1/pluginhost.proto

// 插件-宿主协议（Plugin-Host Protocol）——内核内：宿主 ↔ 本内核插件
// 规格见 docs/dev/architecture/插件契约与协议.md 第二章
//
// MVP 范围与偏离（如实记录）：
//   1) 仅 Handshake + Declare + Invoke + Lifecycle 四个 unary RPC；
//      设计中的 Channel 双向流（宿主↔插件多路复用调用/事件/心跳、插件回调宿主）后续补。
//   2) 方向：MVP 中宿主是 gRPC client、插件是 server，故握手由宿主发起（Hello 宿主→插件），
//      与第二章"插件连上后主动 Hello"方向相反；会话票据仍由宿主签发。
//      待 Channel 落地后回归设计方向。

package pluginhostv1

import (
	v1 "github.com/yandt/VastPlan/shared/go/contract/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lifecycle_Op int32

const (
	Lifecycle_OP_UNSPECIFIED Lifecycle_Op = 0
	Lifecycle_OP_ACTIVATE    Lifecycle_Op = 1
	Lifecycle_OP_DEACTIVATE  Lifecycle_Op = 2
	Lifecycle_OP_DRAIN       Lifecycle_Op = 3
	Lifecycle_OP_SHUTDOWN    Lifecycle_Op = 4
)

// Enum value maps for Lifecycle_Op.
var (
	Lifecycle_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_ACTIVATE",
		2: "OP_DEACTIVATE",
		3: "OP_DRAIN",
		4: "OP_SHUTDOWN",
	}
	Lifecycle_Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_ACTIVATE":    1,
		"OP_DEACTIVATE":  2,
		"OP_DRAIN":       3,
		"OP_SHUTDOWN":    4,
	}
)

func (x Lifecycle_Op) Enum() *Lifecycle_Op {
	p := new(Lifecycle_Op)
	*p = x
	return p
}

func (x Lifecycle_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_pluginhost_v1_pluginhost_proto_enumTypes[0].Descriptor()
}

func (Lifecycle_Op) Type() protoreflect.EnumType {
	return &file_pluginhost_v1_pluginhost_proto_enumTypes[0]
}

func (x Lifecycle_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle_Op.Descriptor instead.
func (Lifecycle_Op) EnumDescriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{7, 0}
}

// 宿主→插件：magic 校验 + 版本协商 + 下发会话票据
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoVersions []int32                `protobuf:"varint,1,rep,packed,name=proto_versions,json=protoVersions,proto3" json:"proto_versions,omitempty"` // 宿主支持的协议版本集
	Magic         string                 `protobuf:"bytes,2,opt,name=magic,proto3" json:"magic,omitempty"`                                              // magic cookie，防误把普通进程当插件
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                     // 宿主签发的会话票据：审计与回调鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtoVersions() []int32 {
	if x != nil {
		return x.ProtoVersions
	}
	return nil
}

func (x *Hello) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *Hello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 插件→宿主：协商结果 + 自报身份 + engines 兼容声明
type HelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NegotiatedProto int32                  `protobuf:"varint,1,opt,name=negotiated_proto,json=negotiatedProto,proto3" json:"negotiated_proto,omitempty"`
	PluginId        string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion   string                 `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// 清单 engines：{内核规范ID: SemVer 范围}，如 {"backend": "^0.1"}。
	// 宿主用它校验自身版本是否满足（ADR-0017 §4 强制点 2）；
	// 未声明本内核 → fail-closed 拒绝装载。
	Engines       map[string]string `protobuf:"bytes,4,rep,name=engines,proto3" json:"engines,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetNegotiatedProto() int32 {
	if x != nil {
		return x.NegotiatedProto
	}
	return 0
}

func (x *HelloAck) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HelloAck) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HelloAck) GetEngines() map[string]string {
	if x != nil {
		return x.Engines
	}
	return nil
}

type Contribution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtensionPoint string                 `protobuf:"bytes,1,opt,name=extension_point,json=extensionPoint,proto3" json:"extension_point,omitempty"` // 目标 Registry 名（= CallTarget.extension_point）
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                               // 贡献稳定逻辑名（= CallTarget.capability），四处同名
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// 该扩展点要求的贡献契约（JSON，见第四章）。
	// 命名带 _json 后缀以避开 protobuf 生成的 Descriptor() 方法冲突。
	DescriptorJson []byte `protobuf:"bytes,4,opt,name=descriptor_json,json=descriptorJson,proto3" json:"descriptor_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contribution) Reset() {
	*x = Contribution{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contribution) ProtoMessage() {}

func (x *Contribution) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contribution.ProtoReflect.Descriptor instead.
func (*Contribution) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{2}
}

func (x *Contribution) GetExtensionPoint() string {
	if x != nil {
		return x.ExtensionPoint
	}
	return ""
}

func (x *Contribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contribution) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Contribution) GetDescriptorJson() []byte {
	if x != nil {
		return x.DescriptorJson
	}
	return nil
}

type DeclareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareRequest) Reset() {
	*x = DeclareRequest{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareRequest) ProtoMessage() {}

func (x *DeclareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareRequest.ProtoReflect.Descriptor instead.
func (*DeclareRequest) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{3}
}

func (x *DeclareRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 插件声明它填充哪些扩展点；宿主据此接入注册表，非法者拒绝（fail-closed）
type Declaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contributions []*Contribution        `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Declaration) Reset() {
	*x = Declaration{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Declaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Declaration) ProtoMessage() {}

func (x *Declaration) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Declaration.ProtoReflect.Descriptor instead.
func (*Declaration) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{4}
}

func (x *Declaration) GetContributions() []*Contribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *v1.CallTarget         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Context       *v1.CallContext        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeRequest) GetTarget() *v1.CallTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InvokeRequest) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v1.CallResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeResponse) GetResult() *v1.CallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Lifecycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Lifecycle_Op           `protobuf:"varint,1,opt,name=op,proto3,enum=vastplan.pluginhost.v1.Lifecycle_Op" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lifecycle) Reset() {
	*x = Lifecycle{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifecycle) ProtoMessage() {}

func (x *Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifecycle.ProtoReflect.Descriptor instead.
func (*Lifecycle) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{7}
}

func (x *Lifecycle) GetOp() Lifecycle_Op {
	if x != nil {
		return x.Op
	}
	return Lifecycle_OP_UNSPECIFIED
}

type LifecycleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleAck) Reset() {
	*x = LifecycleAck{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleAck) ProtoMessage() {}

func (x *LifecycleAck) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleAck.ProtoReflect.Descriptor instead.
func (*LifecycleAck) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{8}
}

func (x *LifecycleAck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *LifecycleAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_pluginhost_v1_pluginhost_proto protoreflect.FileDescriptor

const file_pluginhost_v1_pluginhost_proto_rawDesc = "" +
	"\n" +
	"\x1epluginhost/v1/pluginhost.proto\x12\x16vastplan.pluginhost.v1\x1a\x1acontract/v1/contract.proto\"c\n" +
	"\x05Hello\x12%\n" +
	"\x0eproto_versions\x18\x01 \x03(\x05R\rprotoVersions\x12\x14\n" +
	"\x05magic\x18\x02 \x01(\tR\x05magic\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xfe\x01\n" +
	"\bHelloAck\x12)\n" +
	"\x10negotiated_proto\x18\x01 \x01(\x05R\x0fnegotiatedProto\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12G\n" +
	"\aengines\x18\x04 \x03(\v2-.vastplan.pluginhost.v1.HelloAck.EnginesEntryR\aengines\x1a:\n" +
	"\fEnginesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\fContribution\x12'\n" +
	"\x0fextension_point\x18\x01 \x01(\tR\x0eextensionPoint\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12'\n" +
	"\x0fdescriptor_json\x18\x04 \x01(\fR\x0edescriptorJson\"/\n" +
	"\x0eDeclareRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"Y\n" +
	"\vDeclaration\x12J\n" +
	"\rcontributions\x18\x01 \x03(\v2$.vastplan.pluginhost.v1.ContributionR\rcontributions\"\xa0\x01\n" +
	"\rInvokeRequest\x128\n" +
	"\x06target\x18\x01 \x01(\v2 .vastplan.contract.v1.CallTargetR\x06target\x12;\n" +
	"\acontext\x18\x02 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"d\n" +
	"\x0eInvokeResponse\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .vastplan.contract.v1.CallResultR\x06result\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x9e\x01\n" +
	"\tLifecycle\x124\n" +
	"\x02op\x18\x01 \x01(\x0e2$.vastplan.pluginhost.v1.Lifecycle.OpR\x02op\"[\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOP_ACTIVATE\x10\x01\x12\x11\n" +
	"\rOP_DEACTIVATE\x10\x02\x12\f\n" +
	"\bOP_DRAIN\x10\x03\x12\x0f\n" +
	"\vOP_SHUTDOWN\x10\x04\"O\n" +
	"\fLifecycleAck\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message2\xe1\x02\n" +
	"\n" +
	"PluginHost\x12L\n" +
	"\tHandshake\x12\x1d.vastplan.pluginhost.v1.Hello\x1a .vastplan.pluginhost.v1.HelloAck\x12V\n" +
	"\aDeclare\x12&.vastplan.pluginhost.v1.DeclareRequest\x1a#.vastplan.pluginhost.v1.Declaration\x12W\n" +
	"\x06Invoke\x12%.vastplan.pluginhost.v1.InvokeRequest\x1a&.vastplan.pluginhost.v1.InvokeResponse\x12T\n" +
	"\tLifecycle\x12!.vastplan.pluginhost.v1.Lifecycle\x1a$.vastplan.pluginhost.v1.LifecycleAckB@Z>github.com/yandt/VastPlan/shared/go/pluginhost/v1;pluginhostv1b\x06proto3"

var (
	file_pluginhost_v1_pluginhost_proto_rawDescOnce sync.Once
	file_pluginhost_v1_pluginhost_proto_rawDescData []byte
)

func file_pluginhost_v1_pluginhost_proto_rawDescGZIP() []byte {
	file_pluginhost_v1_pluginhost_proto_rawDescOnce.Do(func() {
		file_pluginhost_v1_pluginhost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginhost_v1_pluginhost_proto_rawDesc), len(file_pluginhost_v1_pluginhost_proto_rawDesc)))
	})
	return file_pluginhost_v1_pluginhost_proto_rawDescData
}

var file_pluginhost_v1_pluginhost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pluginhost_v1_pluginhost_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pluginhost_v1_pluginhost_proto_goTypes = []any{
	(Lifecycle_Op)(0),      // 0: vastplan.pluginhost.v1.Lifecycle.Op
	(*Hello)(nil),          // 1: vastplan.pluginhost.v1.Hello
	(*HelloAck)(nil),       // 2: vastplan.pluginhost.v1.HelloAck
	(*Contribution)(nil),   // 3: vastplan.pluginhost.v1.Contribution
	(*DeclareRequest)(nil), // 4: vastplan.pluginhost.v1.DeclareRequest
	(*Declaration)(nil),    // 5: vastplan.pluginhost.v1.Declaration
	(*InvokeRequest)(nil),  // 6: vastplan.pluginhost.v1.InvokeRequest
	(*InvokeResponse)(nil), // 7: vastplan.pluginhost.v1.InvokeResponse
	(*Lifecycle)(nil),      // 8: vastplan.pluginhost.v1.Lifecycle
	(*LifecycleAck)(nil),   // 9: vastplan.pluginhost.v1.LifecycleAck
	nil,                    // 10: vastplan.pluginhost.v1.HelloAck.EnginesEntry
	(*v1.CallTarget)(nil),  // 11: vastplan.contract.v1.CallTarget
	(*v1.CallContext)(nil), // 12: vastplan.contract.v1.CallContext
	(*v1.CallResult)(nil),  // 13: vastplan.contract.v1.CallResult
}
var file_pluginhost_v1_pluginhost_proto_depIdxs = []int32{
	10, // 0: vastplan.pluginhost.v1.HelloAck.engines:type_name -> vastplan.pluginhost.v1.HelloAck.EnginesEntry
	3,  // 1: vastplan.pluginhost.v1.Declaration.contributions:type_name -> vastplan.pluginhost.v1.Contribution
	11, // 2: vastplan.pluginhost.v1.InvokeRequest.target:type_name -> vastplan.contract.v1.CallTarget
	12, // 3: vastplan.pluginhost.v1.InvokeRequest.context:type_name -> vastplan.contract.v1.CallContext
	13, // 4: vastplan.pluginhost.v1.InvokeResponse.result:type_name -> vastplan.contract.v1.CallResult
	0,  // 5: vastplan.pluginhost.v1.Lifecycle.op:type_name -> vastplan.pluginhost.v1.Lifecycle.Op
	1,  // 6: vastplan.pluginhost.v1.PluginHost.Handshake:input_type -> vastplan.pluginhost.v1.Hello
	4,  // 7: vastplan.pluginhost.v1.PluginHost.Declare:input_type -> vastplan.pluginhost.v1.DeclareRequest
	6,  // 8: vastplan.pluginhost.v1.PluginHost.Invoke:input_type -> vastplan.pluginhost.v1.InvokeRequest
	8,  // 9: vastplan.pluginhost.v1.PluginHost.Lifecycle:input_type -> vastplan.pluginhost.v1.Lifecycle
	2,  // 10: vastplan.pluginhost.v1.PluginHost.Handshake:output_type -> vastplan.pluginhost.v1.HelloAck
	5,  // 11: vastplan.pluginhost.v1.PluginHost.Declare:output_type -> vastplan.pluginhost.v1.Declaration
	7,  // 12: vastplan.pluginhost.v1.PluginHost.Invoke:output_type -> vastplan.pluginhost.v1.InvokeResponse
	9,  // 13: vastplan.pluginhost.v1.PluginHost.Lifecycle:output_type -> vastplan.pluginhost.v1.LifecycleAck
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pluginhost_v1_pluginhost_proto_init() }
func file_pluginhost_v1_pluginhost_proto_init() {
	if File_pluginhost_v1_pluginhost_proto != nil {
		return
	}
	file_pluginhost_v1_pluginhost_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginhost_v1_pluginhost_proto_rawDesc), len(file_pluginhost_v1_pluginhost_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginhost_v1_pluginhost_proto_goTypes,
		DependencyIndexes: file_pluginhost_v1_pluginhost_proto_depIdxs,
		EnumInfos:         file_pluginhost_v1_pluginhost_proto_enumTypes,
		MessageInfos:      file_pluginhost_v1_pluginhost_proto_msgTypes,
	}.Build()
	File_pluginhost_v1_pluginhost_proto = out.File
	file_pluginhost_v1_pluginhost_proto_goTypes = nil
	file_pluginhost_v1_pluginhost_proto_depIdxs = nil
}
