// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: pluginhost/v1/pluginhost.proto

// 插件-宿主协议（Plugin-Host Protocol）——内核内：宿主 ↔ 本内核插件
// 规格见 docs/dev/architecture/插件契约与协议.md 第二章
//
// MVP 范围与偏离（如实记录）：
//   1) 仅 Handshake + Declare + Invoke + Lifecycle 四个 unary RPC；
//      设计中的 Channel 双向流（宿主↔插件多路复用调用/事件/心跳、插件回调宿主）后续补。
//   2) 方向：MVP 中宿主是 gRPC client、插件是 server，故握手由宿主发起（Hello 宿主→插件），
//      与第二章"插件连上后主动 Hello"方向相反；会话票据仍由宿主签发。
//      待 Channel 落地后回归设计方向。

package pluginhostv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginHost_Handshake_FullMethodName = "/vastplan.pluginhost.v1.PluginHost/Handshake"
	PluginHost_Declare_FullMethodName   = "/vastplan.pluginhost.v1.PluginHost/Declare"
	PluginHost_Invoke_FullMethodName    = "/vastplan.pluginhost.v1.PluginHost/Invoke"
	PluginHost_Lifecycle_FullMethodName = "/vastplan.pluginhost.v1.PluginHost/Lifecycle"
)

// PluginHostClient is the client API for PluginHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginHostClient interface {
	Handshake(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloAck, error)
	Declare(ctx context.Context, in *DeclareRequest, opts ...grpc.CallOption) (*Declaration, error)
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	Lifecycle(ctx context.Context, in *Lifecycle, opts ...grpc.CallOption) (*LifecycleAck, error)
}

type pluginHostClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHostClient(cc grpc.ClientConnInterface) PluginHostClient {
	return &pluginHostClient{cc}
}

func (c *pluginHostClient) Handshake(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloAck)
	err := c.cc.Invoke(ctx, PluginHost_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) Declare(ctx context.Context, in *DeclareRequest, opts ...grpc.CallOption) (*Declaration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Declaration)
	err := c.cc.Invoke(ctx, PluginHost_Declare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, PluginHost_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) Lifecycle(ctx context.Context, in *Lifecycle, opts ...grpc.CallOption) (*LifecycleAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifecycleAck)
	err := c.cc.Invoke(ctx, PluginHost_Lifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHostServer is the server API for PluginHost service.
// All implementations must embed UnimplementedPluginHostServer
// for forward compatibility.
type PluginHostServer interface {
	Handshake(context.Context, *Hello) (*HelloAck, error)
	Declare(context.Context, *DeclareRequest) (*Declaration, error)
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	Lifecycle(context.Context, *Lifecycle) (*LifecycleAck, error)
	mustEmbedUnimplementedPluginHostServer()
}

// UnimplementedPluginHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHostServer struct{}

func (UnimplementedPluginHostServer) Handshake(context.Context, *Hello) (*HelloAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginHostServer) Declare(context.Context, *DeclareRequest) (*Declaration, error) {
	return nil, status.Error(codes.Unimplemented, "method Declare not implemented")
}
func (UnimplementedPluginHostServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedPluginHostServer) Lifecycle(context.Context, *Lifecycle) (*LifecycleAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Lifecycle not implemented")
}
func (UnimplementedPluginHostServer) mustEmbedUnimplementedPluginHostServer() {}
func (UnimplementedPluginHostServer) testEmbeddedByValue()                    {}

// UnsafePluginHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHostServer will
// result in compilation errors.
type UnsafePluginHostServer interface {
	mustEmbedUnimplementedPluginHostServer()
}

func RegisterPluginHostServer(s grpc.ServiceRegistrar, srv PluginHostServer) {
	// If the following call panics, it indicates UnimplementedPluginHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHost_ServiceDesc, srv)
}

func _PluginHost_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Handshake(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_Declare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Declare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Declare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Declare(ctx, req.(*DeclareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_Lifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lifecycle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Lifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Lifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Lifecycle(ctx, req.(*Lifecycle))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHost_ServiceDesc is the grpc.ServiceDesc for PluginHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vastplan.pluginhost.v1.PluginHost",
	HandlerType: (*PluginHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PluginHost_Handshake_Handler,
		},
		{
			MethodName: "Declare",
			Handler:    _PluginHost_Declare_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _PluginHost_Invoke_Handler,
		},
		{
			MethodName: "Lifecycle",
			Handler:    _PluginHost_Lifecycle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pluginhost/v1/pluginhost.proto",
}
