import {
  PortalControlError,
  type PortalActivation,
  type PortalBindingRevision,
  type PortalControlClient,
  type PortalGovernanceSnapshot,
  type PortalManagementBinding,
  type PortalPlatformProfile,
  type PortalProfileRevision,
} from "@vastplan/ui-primitives";
import {
  defineCollectionPage,
  jsonSchemaDialect,
  message,
  type CollectionPageDefinition,
  type CollectionQuery,
  type FormSchema,
  type JSONValue,
  type WorkbenchFormDefinition,
} from "@vastplan/workbench-sdk";

const namespace = "cn.vastplan.platform.configuration.portal-composer";
type ProfileRow = PortalProfileRevision & Record<string, unknown>;
type BindingRow = PortalBindingRevision & Record<string, unknown>;
type ActivationRow = PortalActivation & Record<string, unknown>;

const revisionStatusLabels = {
  Draft: message(namespace, "status.draft", "草稿"),
  PendingApproval: message(namespace, "status.pendingApproval", "待审批"),
  Approved: message(namespace, "status.approved", "已批准"),
  Published: message(namespace, "status.published", "已发布"),
};
const revisionStatusTones = { Draft: "neutral", PendingApproval: "warning", Approved: "info", Published: "success" } as const;
const revisionActions = (prefix: string) => [
  { id: `${prefix}.edit`, label: message(namespace, "action.edit", "编辑草稿"), icon: "edit" as const, placement: "page.secondary" as const, requiresSelection: true, form: "edit", visibleWhen: { pointer: "/status", equals: "Draft" } },
  { id: `${prefix}.submit`, label: message(namespace, "governance.action.submit", "提交审批"), icon: "upload" as const, placement: "page.secondary" as const, requiresSelection: true, confirm: message(namespace, "confirm.submit", "提交后不能继续编辑，需要由另一位审批人处理。"), visibleWhen: { pointer: "/status", equals: "Draft" } },
  { id: `${prefix}.approve`, label: message(namespace, "governance.action.approve", "批准"), icon: "success" as const, placement: "page.secondary" as const, tone: "primary" as const, requiresSelection: true, visibleWhen: { pointer: "/status", equals: "PendingApproval" } },
  { id: `${prefix}.publish`, label: message(namespace, "governance.action.publishInput", "发布为可选输入"), icon: "publish" as const, placement: "page.secondary" as const, tone: "primary" as const, requiresSelection: true, confirm: message(namespace, "confirm.inputPublish", "发布只会使该版本可被 Activation 引用，不会直接改变线上 Portal。"), visibleWhen: { pointer: "/status", equals: "Approved" } },
  { id: `${prefix}.preview`, label: message(namespace, "action.preview", "查看内容"), icon: "info" as const, placement: "page.secondary" as const, requiresSelection: true, overlay: "preview" },
];

export const governanceMessages = {
  "zh-CN": {
    "page.profiles.title": "Portal 平台基线", "page.profiles.description": "治理 UI 框架、Shell 模板和导航基线", "page.profiles.navigation": "Portal 平台基线",
    "page.bindings.title": "Portal 服务绑定", "page.bindings.description": "将 Portal 绑定到已发布平台基线和管理服务", "page.bindings.navigation": "Portal 服务绑定",
    "page.activations.title": "Portal 上线记录", "page.activations.description": "以不可变 Activation 组合并切换线上 Portal", "page.activations.navigation": "Portal 上线",
    "governance.action.newFromSelected": "从所选版本新建", "governance.action.submit": "提交审批", "governance.action.approve": "批准", "governance.action.publishInput": "发布为可选输入", "governance.action.activate": "校验并激活", "governance.action.rollback": "回滚到此版本",
    "governance.form.profileId": "Profile ID", "governance.form.renderer": "默认 UI 框架", "governance.form.allowedRenderers": "允许的 UI 框架", "governance.form.userRenderer": "允许用户切换 UI 框架", "governance.form.layout": "默认 Shell 模板", "governance.form.bodyWidth": "页面正文宽度", "governance.form.navigationGroups": "导航分组", "governance.form.portalId": "Portal ID", "governance.form.publishedProfile": "已发布 Profile", "governance.form.services": "管理服务绑定", "governance.form.publishedApplication": "已发布 Application", "governance.form.publishedBinding": "已发布 Binding", "governance.form.expectedActivation": "期望当前 Activation", "governance.form.reason": "变更说明",
    "governance.option.standardLayout": "标准侧栏布局", "governance.option.topLayout": "顶部导航布局", "governance.option.fluid": "自适应", "governance.option.contained": "最大 1280px",
    "column.profile": "Profile", "column.portal": "Portal", "column.status": "状态", "column.updated": "更新时间", "column.inputs": "组合输入", "column.references": "制品引用", "column.time": "时间",
    "status.draft": "草稿", "status.pendingApproval": "待审批", "status.approved": "已批准", "status.published": "已发布", "status.preparing": "准备中", "status.activating": "激活中", "status.current": "当前", "status.superseded": "历史", "status.failed": "失败",
    "status.referencesPending": "同步中", "status.referencesReady": "已保护", "action.edit": "编辑草稿", "action.preview": "查看内容", "action.activate": "创建 Activation", "action.rollback": "回滚", "action.createVersion": "新建版本", "action.createBinding": "新建 Binding",
    "panel.profile": "Profile 版本", "panel.binding": "Binding 版本", "panel.activation": "Activation", "notice.saved": "治理资源已保存", "notice.transitioned": "治理状态已更新", "notice.activated": "Portal 已激活", "notice.rolledBack": "Portal 已回滚", "dialog.preview": "不可变内容预览",
  },
  "en-US": {
    "page.profiles.title": "Portal Platform Profiles", "page.profiles.description": "Govern UI frameworks, Shell templates, and navigation baselines", "page.profiles.navigation": "Portal Profiles",
    "page.bindings.title": "Portal Service Bindings", "page.bindings.description": "Bind Portals to published platform profiles and management services", "page.bindings.navigation": "Portal Bindings",
    "page.activations.title": "Portal Activations", "page.activations.description": "Compose and switch live Portals through immutable Activations", "page.activations.navigation": "Portal Activations",
    "governance.action.newFromSelected": "Create from selected", "governance.action.submit": "Submit", "governance.action.approve": "Approve", "governance.action.publishInput": "Publish as eligible input", "governance.action.activate": "Validate and activate", "governance.action.rollback": "Rollback to this version",
    "governance.form.profileId": "Profile ID", "governance.form.renderer": "Default UI framework", "governance.form.allowedRenderers": "Allowed UI frameworks", "governance.form.userRenderer": "Allow users to switch UI framework", "governance.form.layout": "Default Shell template", "governance.form.bodyWidth": "Page body width", "governance.form.navigationGroups": "Navigation groups", "governance.form.portalId": "Portal ID", "governance.form.publishedProfile": "Published Profile", "governance.form.services": "Management service bindings", "governance.form.publishedApplication": "Published Application", "governance.form.publishedBinding": "Published Binding", "governance.form.expectedActivation": "Expected current Activation", "governance.form.reason": "Change reason",
    "governance.option.standardLayout": "Standard sidebar layout", "governance.option.topLayout": "Top navigation layout", "governance.option.fluid": "Fluid", "governance.option.contained": "Maximum 1280px",
    "column.profile": "Profile", "column.portal": "Portal", "column.status": "Status", "column.updated": "Updated", "column.inputs": "Composition inputs", "column.references": "Artifact references", "column.time": "Time",
    "status.draft": "Draft", "status.pendingApproval": "Pending approval", "status.approved": "Approved", "status.published": "Published", "status.preparing": "Preparing", "status.activating": "Activating", "status.current": "Current", "status.superseded": "Superseded", "status.failed": "Failed",
    "status.referencesPending": "Syncing", "status.referencesReady": "Protected", "action.edit": "Edit draft", "action.preview": "View content", "action.activate": "Create Activation", "action.rollback": "Rollback", "action.createVersion": "New version", "action.createBinding": "New Binding",
    "panel.profile": "Profile version", "panel.binding": "Binding version", "panel.activation": "Activation", "notice.saved": "Governance resource saved", "notice.transitioned": "Governance state updated", "notice.activated": "Portal activated", "notice.rolledBack": "Portal rolled back", "dialog.preview": "Immutable content preview",
  },
} as const;

export function createProfilePage(client: PortalControlClient): CollectionPageDefinition<ProfileRow> {
  const form = (id: "create" | "edit"): WorkbenchFormDefinition<ProfileRow> => ({
    id, schema: profileSchema,
    presentation: { layout: "vertical", navigation: "sections", sections: [{ id: "profile", title: message(namespace, "panel.profile", "Profile 版本"), columns: 2, fields: ["/name", "/defaultRenderer", "/allowedRenderers", "/userSelectableRenderer", "/defaultTemplate", "/pageBodyWidth", "/navigationGroups"] }], fields: [{ pointer: "/navigationGroups", span: 2 }] },
    workflow: { surface: "drawer", size: "lg", title: message(namespace, id === "create" ? "action.createVersion" : "action.edit", id === "create" ? "新建版本" : "编辑草稿"), submitLabel: message(namespace, "action.save", "保存草稿"), success: { notify: message(namespace, "notice.saved", "治理资源已保存"), refreshCollection: true, close: true } },
    async load(selected) { return selected[0] === undefined ? {} : profileValue(selected[0].profile); },
    async submit({ value, selected }) { const base = selected[0]; if (base === undefined) return; const profile = buildProfile(base.profile, value, id === "create"); if (id === "create") await client.createProfile(profile); else await client.updateProfile(base.id, profile); },
  });
  return defineCollectionPage<ProfileRow>({
    id: "platform.portal-composer.profiles", path: "/settings/portals/profiles", title: message(namespace, "page.profiles.title", "Portal 平台基线"), description: message(namespace, "page.profiles.description", "治理 UI 框架、Shell 模板和导航基线"), navigation: { id: "platform.portal-composer.profiles", label: message(namespace, "page.profiles.navigation", "Portal 平台基线"), zone: "settings", order: 10 },
    collection: { id: "portal-profiles", title: message(namespace, "page.profiles.title", "Portal 平台基线"), view: "table", query: pageQuery(), filters: revisionFilters("profile"), columns: [{ key: "id", label: "Revision", format: "number", defaultVisible: true }, { key: "profileId", label: message(namespace, "column.profile", "Profile"), defaultVisible: true, minWidth: 180 }, statusColumn(), updatedColumn()], selection: "single", preferences: { allowedColumns: ["id", "profileId", "status", "updatedAt"], density: true }, actions: [{ id: "profile.create", label: message(namespace, "action.createVersion", "新建版本"), icon: "add", placement: "page.primary", tone: "primary", requiresSelection: true, form: "create" }, ...revisionActions("profile")] },
    forms: [form("create"), form("edit")], overlays: [jsonPreview<ProfileRow>((row) => row.profile as unknown as JSONValue)],
    async load(query, signal) { const snapshot = await client.governance(); const rows = snapshot.profiles.map((row) => ({ ...row, profileId: row.profile.id })) as ProfileRow[]; return selectPage(rows, query, signal, (row, text) => row.profile.id.toLowerCase().includes(text)); },
    async runAction({ action, selected }) { const row = selected[0]; if (row === undefined) return; const transition = action.id.split(".")[1]; if (transition === "submit" || transition === "approve" || transition === "publish") await client.transitionProfile(row.id, transition); return { notify: { title: message(namespace, "notice.transitioned", "治理状态已更新"), kind: "success" } }; },
  });
}

export function createBindingPage(client: PortalControlClient): CollectionPageDefinition<BindingRow> {
  const form = (id: "create" | "edit"): WorkbenchFormDefinition<BindingRow> => ({
    id, schema: bindingSchema([]), presentation: { layout: "vertical", sections: [{ id: "binding", title: message(namespace, "panel.binding", "Binding 版本"), columns: 1, fields: ["/portalId", "/profileRevisionId", "/services"] }] },
    workflow: { surface: "drawer", size: "lg", title: message(namespace, id === "create" ? "action.createBinding" : "action.edit", id === "create" ? "新建 Binding" : "编辑草稿"), submitLabel: message(namespace, "action.save", "保存草稿"), success: { notify: message(namespace, "notice.saved", "治理资源已保存"), refreshCollection: true, close: true } },
    async prepare() { const snapshot = await client.governance(); return { schema: bindingSchema(snapshot.profiles) }; },
    async load(selected) { return selected[0] === undefined ? {} : bindingValue(selected[0]); },
    async submit({ value, selected }) { const base = selected[0]; if (base === undefined) return; const profileRevisionId = Number(value.profileRevisionId); const binding = buildBinding(base.binding, value); if (id === "create") await client.createBinding(profileRevisionId, binding); else await client.updateBinding(base.id, profileRevisionId, binding); },
  });
  return defineCollectionPage<BindingRow>({
    id: "platform.portal-composer.bindings", path: "/settings/portals/bindings", title: message(namespace, "page.bindings.title", "Portal 服务绑定"), description: message(namespace, "page.bindings.description", "将 Portal 绑定到已发布平台基线和管理服务"), navigation: { id: "platform.portal-composer.bindings", label: message(namespace, "page.bindings.navigation", "Portal 服务绑定"), zone: "settings", order: 12 },
    collection: { id: "portal-bindings", title: message(namespace, "page.bindings.title", "Portal 服务绑定"), view: "table", query: pageQuery(), filters: revisionFilters("portalId"), columns: [{ key: "id", label: "Revision", format: "number", defaultVisible: true }, { key: "portalId", label: message(namespace, "column.portal", "Portal"), defaultVisible: true, minWidth: 180 }, { key: "profileRevisionId", label: message(namespace, "column.profile", "Profile"), format: "number", defaultVisible: true }, statusColumn(), updatedColumn()], selection: "single", preferences: { allowedColumns: ["id", "portalId", "profileRevisionId", "status", "updatedAt"], density: true }, actions: [{ id: "binding.create", label: message(namespace, "action.createBinding", "新建 Binding"), icon: "add", placement: "page.primary", tone: "primary", requiresSelection: true, form: "create" }, ...revisionActions("binding")] },
    forms: [form("create"), form("edit")], overlays: [jsonPreview<BindingRow>((row) => row.binding as unknown as JSONValue)],
    async load(query, signal) { const snapshot = await client.governance(); return selectPage(snapshot.bindings as BindingRow[], query, signal, (row, text) => row.portalId.toLowerCase().includes(text)); },
    async runAction({ action, selected }) { const row = selected[0]; if (row === undefined) return; const transition = action.id.split(".")[1]; if (transition === "submit" || transition === "approve" || transition === "publish") await client.transitionBinding(row.id, transition); return { notify: { title: message(namespace, "notice.transitioned", "治理状态已更新"), kind: "success" } }; },
  });
}

export function createActivationPage(client: PortalControlClient): CollectionPageDefinition<ActivationRow> {
  const form: WorkbenchFormDefinition<ActivationRow> = {
    id: "activate", schema: activationSchema(emptySnapshot()), presentation: { layout: "vertical", sections: [{ id: "activation", title: message(namespace, "panel.activation", "Activation"), columns: 2, fields: ["/portalId", "/applicationRevisionId", "/profileRevisionId", "/bindingRevisionId", "/expectedCurrentId", "/reason"] }], fields: [{ pointer: "/reason", span: 2 }] },
    workflow: { surface: "drawer", size: "lg", title: message(namespace, "action.activate", "创建 Activation"), submitLabel: message(namespace, "governance.action.activate", "校验并激活"), success: { notify: message(namespace, "notice.activated", "Portal 已激活"), refreshCollection: true, close: true } },
    async prepare() { const snapshot = await client.governance(); return { schema: activationSchema(snapshot), initialValue: activationDefaults(snapshot) }; },
    async submit({ value }) { const result = await client.activate({ portalId: String(value.portalId ?? ""), applicationRevisionId: Number(value.applicationRevisionId), profileRevisionId: Number(value.profileRevisionId), bindingRevisionId: Number(value.bindingRevisionId), expectedCurrentId: Number(value.expectedCurrentId ?? 0), reason: typeof value.reason === "string" ? value.reason : undefined }); if (result.status === "Failed") throw new Error(result.phases.find((phase) => phase.status === "Failed")?.message ?? "Activation failed"); },
  };
  const activationLabels = { Preparing: message(namespace, "status.preparing", "准备中"), Activating: message(namespace, "status.activating", "激活中"), Current: message(namespace, "status.current", "当前"), Superseded: message(namespace, "status.superseded", "历史"), Failed: message(namespace, "status.failed", "失败") };
  return defineCollectionPage<ActivationRow>({
    id: "platform.portal-composer.activations", path: "/settings/portals/activations", title: message(namespace, "page.activations.title", "Portal 上线记录"), description: message(namespace, "page.activations.description", "以不可变 Activation 组合并切换线上 Portal"), navigation: { id: "platform.portal-composer.activations", label: message(namespace, "page.activations.navigation", "Portal 上线"), zone: "settings", order: 13 },
    collection: { id: "portal-activations", title: message(namespace, "page.activations.title", "Portal 上线记录"), view: "table", query: pageQuery(), filters: [{ id: "portalId", label: message(namespace, "column.portal", "Portal"), kind: "text" }, { id: "status", label: message(namespace, "column.status", "状态"), kind: "select", options: Object.entries(activationLabels).map(([value, label]) => ({ value, label })) }], columns: [{ key: "id", label: "Activation", format: "number", defaultVisible: true }, { key: "portalId", label: message(namespace, "column.portal", "Portal"), defaultVisible: true }, { key: "status", label: message(namespace, "column.status", "状态"), format: "status", valueLabels: activationLabels, statusTones: { Preparing: "info", Activating: "warning", Current: "success", Superseded: "neutral", Failed: "error" }, defaultVisible: true }, { key: "applicationRevisionId", label: "Application", format: "number", defaultVisible: true }, { key: "profileRevisionId", label: "Profile", format: "number", defaultVisible: true }, { key: "bindingRevisionId", label: "Binding", format: "number", defaultVisible: true }, { key: "referencePending", label: message(namespace, "column.references", "制品引用"), format: "status", valueLabels: { true: message(namespace, "status.referencesPending", "同步中"), false: message(namespace, "status.referencesReady", "已保护") }, statusTones: { true: "warning", false: "success" }, defaultVisible: true }, { key: "createdAt", label: message(namespace, "column.time", "时间"), format: "datetime", defaultVisible: true }], selection: "single", preferences: { allowedColumns: ["id", "portalId", "status", "applicationRevisionId", "profileRevisionId", "bindingRevisionId", "referencePending", "createdAt"], density: true }, actions: [{ id: "activation.create", label: message(namespace, "action.activate", "创建 Activation"), icon: "add", placement: "page.primary", tone: "primary", form: "activate" }, { id: "activation.rollback", label: message(namespace, "action.rollback", "回滚"), icon: "refresh", placement: "page.secondary", tone: "danger", requiresSelection: true, confirm: message(namespace, "confirm.rollbackActivation", "将以所选历史输入创建新的 Activation。"), visibleWhen: { pointer: "/status", equals: "Superseded" } }, { id: "activation.preview", label: message(namespace, "action.preview", "查看内容"), icon: "info", placement: "page.secondary", requiresSelection: true, overlay: "preview" }] },
    forms: [form], overlays: [jsonPreview<ActivationRow>((row) => row.resolved as unknown as JSONValue)],
    async load(query, signal) { const snapshot = await client.governance(); return selectPage(snapshot.activations as ActivationRow[], query, signal, (row, text) => row.portalId.toLowerCase().includes(text)); },
    async loadSummary() { const snapshot = await client.governance(); const current = snapshot.activations.filter((item) => item.status === "Current"); return { title: message(namespace, "summary.current", "当前线上 Portal"), metrics: [{ id: "current", label: message(namespace, "summary.currentCount", "当前 Activation"), value: current.length, tone: current.length === 0 ? "warning" : "success" }] }; },
    async runAction({ action, selected }) { const row = selected[0]; if (row === undefined || action.id !== "activation.rollback") return; const snapshot = await client.governance(); const current = snapshot.activations.find((item) => item.portalId === row.portalId && item.status === "Current"); if (current === undefined) throw new Error("No current Activation"); const result = await client.rollbackActivation(row.id, current.id, "管理员从 Portal Workbench 发起回滚"); if (result.status === "Failed") throw new Error(result.phases.find((phase) => phase.status === "Failed")?.message ?? "Activation rollback failed"); return { notify: { title: message(namespace, "notice.rolledBack", "Portal 已回滚"), kind: "success" } }; },
  });
}

export const profileSchema: FormSchema = { id: "portal-profile-editor.v1", schema: { $schema: jsonSchemaDialect, type: "object", additionalProperties: false, required: ["name", "defaultRenderer", "allowedRenderers", "userSelectableRenderer", "defaultTemplate", "pageBodyWidth", "navigationGroups"], properties: {
  name: { type: "string", title: "Profile ID", minLength: 1 }, defaultRenderer: { type: "string", title: "默认 UI 框架", oneOf: [{ const: "arco", title: "Arco Design" }, { const: "mui", title: "Material UI" }] }, allowedRenderers: { type: "array", title: "允许的 UI 框架", minItems: 1, uniqueItems: true, items: { type: "string", oneOf: [{ const: "arco", title: "Arco Design" }, { const: "mui", title: "Material UI" }] } }, userSelectableRenderer: { type: "boolean", title: "允许用户切换 UI 框架" }, defaultTemplate: { type: "string", title: "默认布局", oneOf: [{ const: "standard", title: "标准侧栏布局" }, { const: "top-navigation", title: "顶部导航布局" }] }, pageBodyWidth: { type: "string", title: "页面正文宽度", oneOf: [{ const: "fluid", title: "自适应" }, { const: "contained", title: "最大 1280px" }] }, navigationGroups: { type: "array", title: "导航分组", items: { type: "object", additionalProperties: true } },
} }, uiSchema: { defaultRenderer: { "ui:widget": "select" }, defaultTemplate: { "ui:widget": "select" }, pageBodyWidth: { "ui:widget": "select" } }, localization: { "/properties/name/title": message(namespace, "governance.form.profileId", "Profile ID"), "/properties/defaultRenderer/title": message(namespace, "governance.form.renderer", "默认 UI 框架"), "/properties/allowedRenderers/title": message(namespace, "governance.form.allowedRenderers", "允许的 UI 框架"), "/properties/userSelectableRenderer/title": message(namespace, "governance.form.userRenderer", "允许用户切换 UI 框架"), "/properties/defaultTemplate/title": message(namespace, "governance.form.layout", "默认 Shell 模板"), "/properties/pageBodyWidth/title": message(namespace, "governance.form.bodyWidth", "页面正文宽度"), "/properties/navigationGroups/title": message(namespace, "governance.form.navigationGroups", "导航分组") } };

export function profileValue(profile: PortalPlatformProfile): Record<string, unknown> { return { name: profile.id, defaultRenderer: profile.renderAdapter.config.defaultRenderer === "mui" ? "mui" : "arco", allowedRenderers: profile.renderAdapter.config.allowedRenderers.filter((value) => value === "arco" || value === "mui"), userSelectableRenderer: profile.renderAdapter.config.userSelectable, defaultTemplate: profile.shell.config.defaultTemplate === "top-navigation" ? "top-navigation" : "standard", pageBodyWidth: profile.shell.config.templateOptions?.[profile.shell.config.defaultTemplate]?.pageBodyWidth === "contained" ? "contained" : "fluid", navigationGroups: Array.isArray(profile.shell.config.navigationGroups) ? profile.shell.config.navigationGroups : [] }; }
export function buildProfile(base: PortalPlatformProfile, value: Readonly<Record<string, unknown>>, newRevision: boolean): PortalPlatformProfile { const defaultRenderer = value.defaultRenderer === "mui" ? "mui" : "arco"; const allowedRenderers = Array.isArray(value.allowedRenderers) ? value.allowedRenderers.filter((item): item is string => item === "arco" || item === "mui") : [defaultRenderer]; if (!allowedRenderers.includes(defaultRenderer)) allowedRenderers.unshift(defaultRenderer); const defaultTemplate = value.defaultTemplate === "top-navigation" ? "top-navigation" : "standard"; const templateOptions = { ...(base.shell.config.templateOptions ?? {}), [defaultTemplate]: { ...(base.shell.config.templateOptions?.[defaultTemplate] ?? {}), pageBodyWidth: value.pageBodyWidth as JSONValue } }; return { ...base, id: String(value.name), revision: newRevision ? base.revision + 1 : base.revision, renderAdapter: { ...base.renderAdapter, config: { ...base.renderAdapter.config, defaultRenderer, allowedRenderers, userSelectable: value.userSelectableRenderer === true } }, shell: { ...base.shell, config: { ...base.shell.config, defaultTemplate, navigationGroups: value.navigationGroups as JSONValue, templateOptions } } }; }

export function bindingSchema(profiles: PortalProfileRevision[]): FormSchema { const published = profiles.filter((item) => item.status === "Published"); return { id: "portal-binding-editor.v1", schema: { $schema: jsonSchemaDialect, type: "object", additionalProperties: false, required: ["portalId", "profileRevisionId", "services"], properties: { portalId: { type: "string", title: "Portal ID", minLength: 1 }, profileRevisionId: { type: "integer", title: "Published Profile", oneOf: published.map((item) => ({ const: item.id, title: `${item.profile.id} #${item.id}` })) }, services: { type: "array", title: "管理服务绑定", items: { type: "object", additionalProperties: true } } } }, uiSchema: { profileRevisionId: { "ui:widget": "select" } }, localization: { "/properties/portalId/title": message(namespace, "governance.form.portalId", "Portal ID"), "/properties/profileRevisionId/title": message(namespace, "governance.form.publishedProfile", "已发布 Profile"), "/properties/services/title": message(namespace, "governance.form.services", "管理服务绑定") } }; }
export function bindingValue(revision: PortalBindingRevision): Record<string, unknown> { return { portalId: revision.portalId, profileRevisionId: revision.profileRevisionId, services: revision.binding.services }; }
export function buildBinding(base: PortalManagementBinding, value: Readonly<Record<string, unknown>>): PortalManagementBinding { return { ...base, portalId: String(value.portalId), services: Array.isArray(value.services) ? value.services as PortalManagementBinding["services"] : [] }; }

export function activationSchema(snapshot: PortalGovernanceSnapshot): FormSchema { const apps = snapshot.applications.filter((item) => item.status === "Published"); const profiles = snapshot.profiles.filter((item) => item.status === "Published"); const bindings = snapshot.bindings.filter((item) => item.status === "Published"); return { id: "portal-activation.v1", schema: { $schema: jsonSchemaDialect, type: "object", additionalProperties: false, required: ["portalId", "applicationRevisionId", "profileRevisionId", "bindingRevisionId", "expectedCurrentId"], properties: { portalId: { type: "string", title: "Portal ID", oneOf: [...new Set(bindings.map((item) => item.portalId))].map((id) => ({ const: id, title: id })) }, applicationRevisionId: { type: "integer", title: "Published Application", oneOf: apps.map((item) => ({ const: item.id, title: `${item.portalId} #${item.id}` })) }, profileRevisionId: { type: "integer", title: "Published Profile", oneOf: profiles.map((item) => ({ const: item.id, title: `${item.profile.id} #${item.id}` })) }, bindingRevisionId: { type: "integer", title: "Published Binding", oneOf: bindings.map((item) => ({ const: item.id, title: `${item.portalId} #${item.id}` })) }, expectedCurrentId: { type: "integer", title: "Expected current Activation", minimum: 0, default: 0 }, reason: { type: "string", title: "Change reason" } } }, uiSchema: { portalId: { "ui:widget": "select" }, applicationRevisionId: { "ui:widget": "select" }, profileRevisionId: { "ui:widget": "select" }, bindingRevisionId: { "ui:widget": "select" } }, localization: { "/properties/portalId/title": message(namespace, "governance.form.portalId", "Portal ID"), "/properties/applicationRevisionId/title": message(namespace, "governance.form.publishedApplication", "已发布 Application"), "/properties/profileRevisionId/title": message(namespace, "governance.form.publishedProfile", "已发布 Profile"), "/properties/bindingRevisionId/title": message(namespace, "governance.form.publishedBinding", "已发布 Binding"), "/properties/expectedCurrentId/title": message(namespace, "governance.form.expectedActivation", "期望当前 Activation"), "/properties/reason/title": message(namespace, "governance.form.reason", "变更说明") } }; }
export function activationDefaults(snapshot: PortalGovernanceSnapshot): Record<string, unknown> { const binding = snapshot.bindings.find((item) => item.status === "Published"); if (binding === undefined) return {}; const application = snapshot.applications.find((item) => item.status === "Published" && item.portalId === binding.portalId); const current = snapshot.activations.find((item) => item.status === "Current" && item.portalId === binding.portalId); return { portalId: binding.portalId, applicationRevisionId: application?.id, profileRevisionId: binding.profileRevisionId, bindingRevisionId: binding.id, expectedCurrentId: current?.id ?? 0, reason: "" }; }

function pageQuery() { return { mode: "page" as const, defaultPageSize: 20, pageSizeOptions: [10, 20, 50] }; }
function revisionFilters(textID: string) { return [{ id: textID, label: message(namespace, textID === "profile" ? "column.profile" : "column.portal", textID === "profile" ? "Profile" : "Portal"), kind: "text" as const }, { id: "status", label: message(namespace, "column.status", "状态"), kind: "select" as const, options: Object.entries(revisionStatusLabels).map(([value, label]) => ({ value, label })) }]; }
function statusColumn() { return { key: "status", label: message(namespace, "column.status", "状态"), format: "status" as const, valueLabels: revisionStatusLabels, statusTones: revisionStatusTones, defaultVisible: true, minWidth: 120 }; }
function updatedColumn() { return { key: "updatedAt", label: message(namespace, "column.updated", "更新时间"), format: "datetime" as const, defaultVisible: true, minWidth: 180 }; }
function jsonPreview<Row extends Record<string, unknown>>(value: (row: Row) => JSONValue) { return { id: "preview", surface: "drawer" as const, size: "lg" as const, title: message(namespace, "dialog.preview", "不可变内容预览"), async load(selected: readonly Row[]) { return { kind: "json" as const, documents: selected[0] === undefined ? [] : [{ value: value(selected[0]) }] }; } }; }
function selectPage<Row extends { status: string }>(rows: Row[], query: CollectionQuery, signal: AbortSignal, matchesText: (row: Row, text: string) => boolean) { if (signal.aborted) return { items: [], total: 0 }; const text = Object.entries(query.filters).find(([key]) => key !== "status")?.[1]; const needle = typeof text === "string" ? text.trim().toLowerCase() : ""; const status = typeof query.filters.status === "string" ? query.filters.status : ""; const filtered = rows.filter((row) => (needle === "" || matchesText(row, needle)) && (status === "" || row.status === status)); const start = (query.page - 1) * query.pageSize; return { items: filtered.slice(start, start + query.pageSize), total: filtered.length }; }
function emptySnapshot(): PortalGovernanceSnapshot { return { profiles: [], applications: [], bindings: [], activations: [] }; }

export function portalControlError(cause: unknown): string { return cause instanceof PortalControlError ? cause.code : cause instanceof Error ? cause.message : "request_rejected"; }
