package datamodelgen

import (
	"bytes"
	"fmt"
	"go/format"

	datamodelv1 "cdsoft.com.cn/VastPlan/contracts/schemas/datamodel/v1"
)

func generateGo(model datamodelv1.Model, packageName string) (Output, error) {
	name := exportedName(model.ID)
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by datamodelgen; DO NOT EDIT.\npackage %s\n\nimport (\n\t\"context\"\n\t\"encoding/json\"\n", packageName)
	if modelUsesType(model, "timestamp") {
		out.WriteString("\t\"time\"\n")
	}
	out.WriteString(")\n\n")
	fmt.Fprintf(&out, "const %sModelID = %q\nconst %sSchemaVersion uint64 = %d\n\n", name, model.ID, name, model.SchemaVersion)
	fmt.Fprintf(&out, "type %s struct {\n", name)
	for _, field := range model.Fields {
		fmt.Fprintf(&out, "\t%s %s `json:\"%s\"`\n", exportedName(field.ID), goType(field), field.ID)
	}
	out.WriteString("}\n\n")
	fmt.Fprintf(&out, "type %sListOptions struct { Cursor string; Limit int; Filter map[string]any; Sort []string }\n", name)
	fmt.Fprintf(&out, "type %sPage struct { Items []%s; NextCursor string }\n", name, name)
	fmt.Fprintf(&out, "type %sRepository interface {\n", name)
	fmt.Fprintf(&out, "\tCreate(context.Context, %s, string) (%s, error)\n", name, name)
	fmt.Fprintf(&out, "\tGet(context.Context, map[string]any) (%s, error)\n", name)
	fmt.Fprintf(&out, "\tList(context.Context, %sListOptions) (%sPage, error)\n", name, name)
	fmt.Fprintf(&out, "\tUpdate(context.Context, %s, int64, string) (%s, error)\n", name, name)
	out.WriteString("\tDelete(context.Context, map[string]any, int64, string) error\n")
	fmt.Fprintf(&out, "\tBatch(context.Context, []%s, string) ([]%s, error)\n", name, name)
	out.WriteString("\tUnitOfWork(context.Context, func(context.Context) error) error\n\tAppendOutbox(context.Context, string, json.RawMessage, string) error\n}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return Output{}, fmt.Errorf("格式化 Go 生成物: %w", err)
	}
	return Output{Filename: fileStem(model.ID) + "_generated.go", Content: formatted}, nil
}

func modelUsesType(model datamodelv1.Model, fieldType string) bool {
	for _, field := range model.Fields {
		if field.Type == fieldType {
			return true
		}
	}
	return false
}

func goType(field datamodelv1.Field) string {
	value := map[string]string{"string": "string", "uuid": "string", "int64": "int64", "float64": "float64", "bool": "bool", "bytes": "[]byte", "timestamp": "time.Time", "json": "json.RawMessage"}[field.Type]
	if field.Nullable {
		return "*" + value
	}
	return value
}
