package datamodelgen

import (
	"bytes"
	"fmt"

	datamodelv1 "cdsoft.com.cn/VastPlan/contracts/schemas/datamodel/v1"
)

func generatePython(model datamodelv1.Model) []byte {
	name := exportedName(model.ID)
	var out bytes.Buffer
	out.WriteString("# Code generated by datamodelgen; DO NOT EDIT.\nfrom __future__ import annotations\n\nfrom dataclasses import dataclass\nfrom datetime import datetime\nfrom typing import Any, Awaitable, Callable, Protocol, TypeVar\n\n")
	fmt.Fprintf(&out, "MODEL_ID = %q\nSCHEMA_VERSION = %d\nT = TypeVar(\"T\")\n\n@dataclass(frozen=True, slots=True)\nclass %s:\n", model.ID, model.SchemaVersion, name)
	for _, field := range model.Fields {
		fmt.Fprintf(&out, "    %s: %s\n", pythonName(field.ID), pyType(field))
	}
	out.WriteString("\nclass RepositoryTransaction(Protocol):\n    id: str\n")
	fmt.Fprintf(&out, "\nclass %sRepository(Protocol):\n", name)
	fmt.Fprintf(&out, "    async def create(self, value: %s, idempotency_key: str) -> %s: ...\n", name, name)
	fmt.Fprintf(&out, "    async def get(self, key: dict[str, Any]) -> %s: ...\n", name)
	fmt.Fprintf(&out, "    async def list(self, *, cursor: str | None = None, limit: int = 100, filter: dict[str, Any] | None = None, sort: tuple[str, ...] = ()) -> tuple[list[%s], str | None]: ...\n", name)
	fmt.Fprintf(&out, "    async def update(self, value: %s, expected_revision: int, idempotency_key: str) -> %s: ...\n", name, name)
	out.WriteString("    async def delete(self, key: dict[str, Any], expected_revision: int, idempotency_key: str) -> None: ...\n")
	fmt.Fprintf(&out, "    async def batch(self, values: list[%s], idempotency_key: str) -> list[%s]: ...\n", name, name)
	out.WriteString("    async def unit_of_work(self, work: Callable[[RepositoryTransaction], Awaitable[T]]) -> T: ...\n")
	out.WriteString("    async def append_outbox(self, topic: str, payload: Any, idempotency_key: str) -> None: ...\n")
	return out.Bytes()
}

func pyType(field datamodelv1.Field) string {
	value := map[string]string{"string": "str", "uuid": "str", "int64": "int", "float64": "float", "bool": "bool", "bytes": "bytes", "timestamp": "datetime", "json": "Any"}[field.Type]
	if field.Nullable {
		return value + " | None"
	}
	return value
}
