package datamodelgen

import (
	"bytes"
	"fmt"

	datamodelv1 "cdsoft.com.cn/VastPlan/contracts/schemas/datamodel/v1"
)

func generateTypeScript(model datamodelv1.Model, modelSHA256 string) []byte {
	name := exportedName(model.ID)
	var out bytes.Buffer
	out.WriteString("// Code generated by datamodelgen; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "export const %sModelId = %q as const;\nexport const %sModelSha256 = %q as const;\nexport const %sSchemaVersion = %d as const;\n\n", name, model.ID, name, modelSHA256, name, model.SchemaVersion)
	fmt.Fprintf(&out, "export interface %s {\n", name)
	for _, field := range model.Fields {
		fmt.Fprintf(&out, "  %s: %s;\n", field.ID, tsType(field))
	}
	out.WriteString("}\n\n")
	fmt.Fprintf(&out, "export interface %sRepositoryClient {\n", name)
	fmt.Fprintf(&out, "  create(value: %s, idempotencyKey: string, signal?: AbortSignal): Promise<%s>;\n", name, name)
	fmt.Fprintf(&out, "  get(key: Readonly<Record<string, unknown>>, signal?: AbortSignal): Promise<%s>;\n", name)
	fmt.Fprintf(&out, "  list(options: Readonly<{ cursor?: string; limit?: number; filter?: Readonly<Record<string, unknown>>; sort?: readonly string[] }>, signal?: AbortSignal): Promise<Readonly<{ items: readonly %s[]; nextCursor?: string }>>;\n", name)
	fmt.Fprintf(&out, "  update(value: %s, expectedRevision: number, idempotencyKey: string, signal?: AbortSignal): Promise<%s>;\n", name, name)
	out.WriteString("  delete(key: Readonly<Record<string, unknown>>, expectedRevision: number, idempotencyKey: string, signal?: AbortSignal): Promise<void>;\n")
	fmt.Fprintf(&out, "  batch(values: readonly %s[], idempotencyKey: string, signal?: AbortSignal): Promise<readonly %s[]>;\n", name, name)
	out.WriteString("  unitOfWork<T>(work: (transaction: RepositoryTransaction) => Promise<T>, signal?: AbortSignal): Promise<T>;\n")
	out.WriteString("  appendOutbox(topic: string, payload: unknown, idempotencyKey: string, signal?: AbortSignal): Promise<void>;\n}\n\n")
	out.WriteString("export interface RepositoryTransaction { readonly id: string; }\n")
	return out.Bytes()
}

func tsType(field datamodelv1.Field) string {
	value := map[string]string{"string": "string", "uuid": "string", "int64": "string", "float64": "number", "bool": "boolean", "bytes": "Uint8Array", "timestamp": "string", "json": "unknown"}[field.Type]
	if field.Nullable {
		return value + " | null"
	}
	return value
}
