import type { AuthorizationRoleRevision, AuthorizationStatement, PlatformAdminClient } from "@vastplan/platform-admin";
import { defineCollectionPage, jsonSchemaDialect, message, type CollectionPageDefinition, type FormSchema, type WorkbenchFormDefinition } from "@vastplan/workbench-sdk";
import { namespace, page } from "../model.js";

type RoleRow = AuthorizationRoleRevision & Record<string, unknown>;

export function rolesPage(client: PlatformAdminClient): CollectionPageDefinition<RoleRow> {
  const create = roleForm(client,"create");
  const edit = roleForm(client,"edit");
  const labels = {Draft:message(namespace,"status.draft","草稿"),PendingApproval:message(namespace,"status.pending","待审批"),Approved:message(namespace,"status.approved","已批准"),Published:message(namespace,"status.published","已发布"),Retired:message(namespace,"status.retired","已退役")};
  return defineCollectionPage<RoleRow>({
    id:"platform.authorization.roles",path:"/settings/authorization/roles",title:message(namespace,"roles.title","角色管理"),description:message(namespace,"roles.description","角色按 revision 审批和发布，不能引用权限目录以外的代码。"),requiredPermissions:["platform.authorization.catalog"],requiredAnyPermissions:["platform.authorization.role","platform.authorization.approve","platform.authorization.publish"],navigation:{id:"platform.authorization.roles",label:message(namespace,"roles.navigation","角色"),zone:"settings",groupID:"platform.authorization",order:20},
    collection:{id:"authorization-roles",title:message(namespace,"roles.title","角色管理"),view:"table",query:{mode:"page",defaultPageSize:20,pageSizeOptions:[20,50]},filters:[{id:"search",label:message(namespace,"filter.role","角色 ID 或名称"),kind:"text"}],columns:[{key:"id",label:message(namespace,"column.roleId","角色 ID"),defaultVisible:true,minWidth:220},{key:"revision",label:message(namespace,"column.revision","Revision"),format:"number",defaultVisible:true},{key:"title",label:message(namespace,"column.title","名称"),defaultVisible:true},{key:"state",label:message(namespace,"column.status","状态"),format:"status",valueLabels:labels,statusTones:{Draft:"neutral",PendingApproval:"warning",Approved:"info",Published:"success",Retired:"neutral"},defaultVisible:true},{key:"createdBy",label:message(namespace,"column.creator","创建人"),defaultVisible:true},{key:"approvedBy",label:message(namespace,"column.approver","审批人"),defaultVisible:true},{key:"updatedAt",label:message(namespace,"column.updated","更新时间"),format:"datetime",defaultVisible:true}],selection:"single",preferences:{allowedColumns:["id","revision","title","state","createdBy","approvedBy","updatedAt"],density:true},actions:[
      {id:"create",label:message(namespace,"action.createRole","新建角色"),icon:"add",placement:"page.primary",tone:"primary",form:"create",requiredPermissions:["platform.authorization.role"]},
      {id:"publishSnapshot",label:message(namespace,"action.publishSnapshot","发布策略快照"),icon:"publish",placement:"page.secondary",tone:"primary",requiredPermissions:["platform.authorization.publish"]},
      {id:"edit",label:message(namespace,"action.edit","编辑"),placement:"record.row",form:"edit",requiredPermissions:["platform.authorization.role"],visibleWhen:{pointer:"/state",equals:"Draft"}},
      {id:"submit",label:message(namespace,"action.submit","提交审批"),placement:"record.row",requiredPermissions:["platform.authorization.role"],visibleWhen:{pointer:"/state",equals:"Draft"}},
      {id:"approve",label:message(namespace,"action.approve","批准"),placement:"record.row",requiredPermissions:["platform.authorization.approve"],visibleWhen:{pointer:"/state",equals:"PendingApproval"}},
      {id:"publish",label:message(namespace,"action.publish","发布"),placement:"record.row",requiredPermissions:["platform.authorization.publish"],visibleWhen:{pointer:"/state",equals:"Approved"}},
      {id:"retire",label:message(namespace,"action.retire","退役"),placement:"record.row",tone:"danger",requiredPermissions:["platform.authorization.role"],confirm:message(namespace,"confirm.retireRole","确认退役该角色 revision？"),visibleWhen:{pointer:"/state",equals:"Published"}}
    ]},forms:[create,edit],
    async load(query,signal){const state=await client.getAuthorizationPolicy();if(signal.aborted)return{items:[],total:0};return page(state.roles as RoleRow[],query,(row,text)=>row.id.toLowerCase().includes(text)||row.title.toLowerCase().includes(text));},
    async runAction({action,selected}){if(action.id==="publishSnapshot"){const state=await client.getAuthorizationPolicy();await client.publishAuthorizationSnapshot(state.generation,[],300,"管理员发布授权策略");return{notify:{title:message(namespace,"notice.snapshotPublished","策略快照已发布"),kind:"success"}};}const row=selected[0];if(row===undefined||!["submit","approve","publish","retire"].includes(action.id))return;const state=await client.getAuthorizationPolicy();await client.transitionAuthorizationRole(row.id,row.revision,action.id as "submit"|"approve"|"publish"|"retire",state.generation);return{notify:{title:action.label,kind:"success"}};}
  });
}

function roleForm(client:PlatformAdminClient,mode:"create"|"edit"):WorkbenchFormDefinition<RoleRow>{
  const base:FormSchema={id:`authorization-role-${mode}.v1`,schema:{$schema:jsonSchemaDialect,type:"object",additionalProperties:false,required:["id","title","permissions"],properties:{id:{type:"string",title:"Role ID",minLength:1,maxLength:160},title:{type:"string",title:"名称",minLength:1,maxLength:160},description:{type:"string",title:"说明",maxLength:1000},permissions:{type:"array",title:"权限",minItems:1,uniqueItems:true,items:{type:"string"}}}},localization:{"/properties/id/title":message(namespace,"form.roleId","Role ID"),"/properties/title/title":message(namespace,"form.title","名称"),"/properties/description/title":message(namespace,"form.description","说明"),"/properties/permissions/title":message(namespace,"form.permissions","权限")}};
  return{id:mode,schema:base,presentation:{layout:"vertical",navigation:"sections",sections:[{id:"role",title:message(namespace,"form.roleSection","角色定义"),columns:2,fields:["/id","/title","/description","/permissions"]}],fields:[{pointer:"/description",span:2},{pointer:"/permissions",span:2}]},workflow:{surface:"drawer",size:"lg",title:message(namespace,mode==="create"?"action.createRole":"action.edit","角色定义"),submitLabel:message(namespace,"action.save","保存"),success:{notify:message(namespace,"notice.roleSaved","角色已保存"),refreshCollection:true,close:true}},async prepare(){const state=await client.getAuthorizationPolicy();const root=base.schema as Record<string,unknown>;const properties=root.properties as Record<string,unknown>;return{schema:{...base,schema:{...root,properties:{...properties,permissions:{type:"array",title:"权限",minItems:1,uniqueItems:true,items:{type:"string",oneOf:state.catalog.permissions.filter(item=>item.assignable).map(item=>({const:item.code,title:`${item.title} · ${item.code}`}))}}}}} as FormSchema};},async load(selected){const row=selected[0];if(row===undefined)return{};return{id:row.id,title:row.title,description:row.description??"",permissions:[...new Set(row.statements.flatMap(item=>item.permissions))]};},async submit({value,selected}){const permissions=Array.isArray(value.permissions)?value.permissions.filter((item):item is string=>typeof item==="string"):[];const statement:AuthorizationStatement={id:"managed-allow",effect:"allow",permissions,constraints:[]};const state=await client.getAuthorizationPolicy();if(mode==="create")await client.createAuthorizationRole({expectedGeneration:state.generation,id:String(value.id??""),domainId:"platform.root",title:String(value.title??""),description:typeof value.description==="string"?value.description:undefined,statements:[statement]});else{const row=selected[0];if(row!==undefined)await client.updateAuthorizationRole(row.id,row.revision,{expectedGeneration:state.generation,title:String(value.title??""),description:typeof value.description==="string"?value.description:undefined,statements:[statement]});}}};
}
