export const localization = {
  defaultLocale: "zh-CN",
  messages: {
    "zh-CN": {
      "page.title": "制品仓库", "page.titleService": "制品仓库 · {service}",
      "page.catalog.description": "查询可信制品、发布者、目标内核与生命周期",
      "page.capacity.title": "容量与配额", "page.capacity.navigation": "容量与配额", "page.capacity.description": "查看累积配额、活动用量与隔离占用",
      "page.references.title": "制品引用", "page.references.navigation": "制品引用", "page.references.description": "查看阻止垃圾回收的消费者完整快照",
      "page.gc.title": "垃圾回收", "page.gc.navigation": "垃圾回收", "page.gc.description": "按计划隔离并在宽限期后复核清扫",
      "page.migration.title": "存储迁移", "page.migration.navigation": "存储迁移", "page.migration.description": "按阶段准备、同步、切换、观察、回滚并安全释放旧 Volume",
      "page.publication.title": "发布审批", "page.publication.navigation": "发布审批", "page.publication.description": "以双人分离审批将已验签 testing 制品晋级到 stable",
      "page.assessment.title": "安全评估", "page.assessment.navigation": "安全评估", "page.assessment.description": "查看仓库已接受的扫描数据库 revision 与报告归档状态；Source/Provider/Controller 配置统一在插件配置中审批发布",
      "panel.catalog": "制品目录", "panel.overview": "仓库概览", "panel.quotas": "配额用量", "panel.capacity": "容量", "panel.references": "引用快照",
      "panel.gc": "隔离与清扫记录", "panel.gcPlan": "当前回收计划", "panel.migration": "当前迁移", "panel.migrationStatus": "迁移状态",
      "panel.publications": "发布申请", "filter.publicationStatus": "审批状态",
      "panel.assessmentRevisions": "已使用数据库 Revision", "panel.assessmentOverview": "评估证据状态",
      "filter.plugin": "插件 ID / 命名空间", "filter.namespace": "命名空间", "filter.publisher": "发布者", "filter.channel": "通道", "filter.target": "目标内核",
      "filter.lifecycle": "生命周期", "filter.exceeded": "仅超限", "filter.ownerKind": "Owner 类型", "filter.gcStatus": "回收状态",
      "column.plugin": "插件 ID", "column.version": "版本", "column.channel": "通道", "column.publisher": "发布者", "column.targets": "目标内核", "column.size": "大小",
      "column.lifecycle": "生命周期", "column.sbom": "SBOM", "column.pythonLock": "Python 锁", "column.provenance": "来源证明", "column.security": "安全准入", "column.revision": "仓库 Revision", "column.publishedAt": "发布时间", "column.quota": "配额", "column.scope": "作用范围",
	  "security.passed": "复扫通过", "security.failed": "复扫失败", "security.stale": "复扫过期", "security.admitted": "准入通过", "security.missing": "未提供",
      "column.artifacts": "制品数", "column.artifactLimit": "数量上限", "column.bytes": "对象字节", "column.byteLimit": "字节上限", "column.state": "状态",
      "column.tenant": "租户", "column.ownerKind": "Owner 类型", "column.ownerId": "Owner ID", "column.referencePublisher": "可信发布者", "column.generation": "Generation",
      "column.referenceCount": "引用数", "column.expiresAt": "租约到期", "column.gcStatus": "回收状态", "column.sweepAfter": "最早清扫时间",
      "column.migrationId": "迁移 ID", "column.migrationPhase": "阶段", "column.migrationSource": "源存储", "column.migrationTarget": "目标存储",
      "column.migrationFiles": "文件数", "column.migrationBytes": "已同步", "column.migrationDigest": "同步摘要", "column.migrationObservation": "观察期结束", "column.migrationConfigured": "配置已切换", "column.migrationError": "最近错误",
      "column.publicationStatus": "审批状态", "column.keyId": "签名 Key", "column.publicationReason": "发布原因", "column.submittedBy": "提交人", "column.approvedBy": "批准人", "column.submittedAt": "提交时间", "column.publicationExpiresAt": "有效期至", "column.publicationPublishedAt": "发布时间", "column.publicationTerminalReason": "终止原因", "column.publicationTerminalBy": "终止人", "column.publicationTerminalAt": "终止时间",
      "column.databaseRevision": "数据库 Revision", "column.current": "当前有效", "column.failed": "失败", "column.stale": "过期", "column.invalid": "无效", "column.lastEvaluatedAt": "最近评估",
      "metric.status": "服务状态", "metric.activeArtifacts": "活动制品", "metric.storedBytes": "实际存储", "metric.quota": "配额状态", "metric.security": "安全准入", "metric.provider": "存储 Provider",
      "metric.volume": "活动 Volume", "metric.catalogRevision": "Catalog Revision", "metric.migration": "迁移状态", "metric.activeBytes": "活动字节",
      "metric.quarantinedBytes": "隔离字节", "metric.reclaimedBytes": "已回收", "metric.gcReady": "可执行", "metric.gcCandidates": "候选制品",
      "metric.gcBytes": "候选字节", "metric.gcBlockers": "阻断原因", "metric.migrationPhase": "当前阶段", "metric.migrationFiles": "已校验文件",
      "metric.migrationBytes": "已校验字节", "metric.migrationRollback": "可回滚", "metric.migrationConfiguration": "运行配置",
      "metric.reportArchive": "报告归档", "metric.databaseRevisions": "数据库 Revision", "metric.assessmentAlerts": "异常评估", "metric.unassessed": "未评估制品",
      "action.lifecycle": "变更生命周期", "action.lifecycle.save": "确认变更", "action.quarantine": "隔离当前计划", "action.sweep": "清扫到期制品",
      "action.migration.prepare": "准备迁移", "action.migration.sync": "增量同步", "action.migration.cutover": "切换", "action.migration.rollback": "回滚",
      "action.migration.finalize": "确认迁移", "action.migration.release": "释放旧 Volume",
      "action.publication.submit": "提交发布审批", "action.publication.approve": "批准", "action.publication.reject": "驳回", "action.publication.cancel": "撤销", "action.evidence": "供应链证据",
      "action.vulnerabilityReport": "下载漏洞报告", "action.licenseReport": "下载许可证报告",
      "provenance.verified": "已验证", "provenance.missing": "未提供",
      "form.lifecycle.status": "生命周期", "form.lifecycle.reason": "变更原因", "form.lifecycle.replacementPlugin": "替代插件 ID",
      "form.lifecycle.replacementConstraint": "替代版本约束", "form.lifecycle.transition": "生命周期变更", "form.lifecycle.replacement": "弃用替代方案",
      "form.lifecycle.replacementHelp": "仅 deprecated 状态可以声明替代插件和 SemVer 约束。", "form.lifecycle.title": "变更制品生命周期",
      "form.lifecycle.description": "变更使用 Catalog revision CAS 写入审计流水；revoked 为不可逆安全状态。",
      "form.migration.id": "迁移 ID", "form.migration.provider": "目标 Provider", "form.migration.volume": "目标 Volume", "form.migration.target": "迁移目标",
      "form.migration.observation": "观察期（秒）", "form.migration.prepareTitle": "准备存储迁移", "form.migration.prepareDescription": "V1 只支持同一 File Provider 下的空目标 Volume。准备阶段不会切换活动仓库。",
      "form.migration.cutoverTitle": "切换活动 Volume", "form.migration.cutoverDescription": "系统先做最终增量同步，再原子切换并进入双写观察期。",
      "form.publication.reason": "发布原因", "form.publication.revision": "审批 Revision", "form.publication.title": "提交 stable 发布审批", "form.publication.description": "审批精确绑定当前 testing 制品、发布者签名、来源证明 sidecar 与目标 stable ref。批准人必须是另一位用户。",
      "form.publication.rejectReason": "驳回原因", "form.publication.cancelReason": "撤销原因", "form.publication.rejectTitle": "驳回发布审批", "form.publication.cancelTitle": "撤销发布审批", "form.publication.rejectDescription": "驳回会立即使当前 stable 发布授权失效；提交人与驳回人必须分离。", "form.publication.cancelDescription": "只有原提交人可以撤销，撤销后该申请不可恢复。",
      "confirm.lifecycle": "生命周期变更会影响新的解析和交付，请确认原因与替代版本均准确。",
      "confirm.quarantine": "将重新生成计划并隔离全部候选，默认宽限期为 72 小时。", "confirm.sweep": "只会删除已超过宽限期且复核无引用的隔离制品。",
      "confirm.migration.prepare": "系统将探测并绑定目标 Volume，请确认目标为空且未被其他服务使用。", "confirm.migration.cutover": "切换会短暂冻结发布；读取不会中断。",
      "confirm.migration.rollback": "确认回滚到源 Volume？观察期内的新写入已双写，可安全回退。", "confirm.migration.finalize": "确认结束双写观察期？完成后不能再回滚。",
      "confirm.migration.release": "确认配置已指向目标 Volume，并隔离释放旧 Volume？",
      "confirm.publication.approve": "确认该 testing 制品可晋级 stable？系统会强制提交人与批准人分离。",
      "notice.lifecycleSaved": "制品生命周期已更新", "notice.migrationPrepared": "迁移已准备", "notice.migrationCutover": "仓库已进入观察期",
      "notice.publicationSubmitted": "发布审批已提交", "notice.publicationApproved": "发布审批已批准", "notice.publicationRejected": "发布审批已驳回", "notice.publicationCancelled": "发布审批已撤销", "overlay.evidence.title": "供应链证据", "overlay.evidence.document": "已验证制品与审批轨迹",
      "error.lifecycle.replacementPair": "替代插件与版本约束必须同时填写", "error.lifecycle.replacementDeprecated": "只有 deprecated 状态可以声明替代制品",
      "error.lifecycle.required": "请选择状态并填写变更原因", "error.lifecycle.same": "请选择不同于当前状态的新状态",
      "lifecycle.active": "活动", "lifecycle.deprecated": "已弃用", "lifecycle.yanked": "已下架", "lifecycle.revoked": "已撤销",
      "migration.none": "未开始", "migration.prepared": "已准备", "migration.synced": "已同步", "migration.observing": "观察中", "migration.finalized": "已确认", "migration.rolledBack": "已回滚", "migration.released": "已释放",
      "publication.PendingApproval": "待批准", "publication.Approved": "已批准", "publication.Published": "已发布", "publication.Rejected": "已驳回", "publication.Cancelled": "已撤销", "publication.Expired": "已过期",
      "sbom.bound": "已绑定", "sbom.missing": "未提供",
      "pythonLock.bound": "已闭合", "pythonLock.missing": "不适用",
    },
    "en-US": {
      "page.title": "Artifact repository", "page.titleService": "Artifact repository · {service}",
      "page.catalog.description": "Query trusted artifacts, publishers, targets, and lifecycle",
      "page.capacity.title": "Capacity and quotas", "page.capacity.navigation": "Capacity and quotas", "page.capacity.description": "Inspect cumulative quotas, active usage, and quarantine storage",
      "page.references.title": "Artifact references", "page.references.navigation": "Artifact references", "page.references.description": "Inspect complete consumer snapshots that protect artifacts from GC",
      "page.gc.title": "Garbage collection", "page.gc.navigation": "Garbage collection", "page.gc.description": "Quarantine by plan and sweep only after the grace period",
      "page.migration.title": "Storage migration", "page.migration.navigation": "Storage migration", "page.migration.description": "Prepare, sync, cut over, observe, roll back, and safely release storage volumes",
      "page.publication.title": "Publication approvals", "page.publication.navigation": "Publication approvals", "page.publication.description": "Promote verified testing artifacts to stable with two-person approval",
      "page.assessment.title": "Security assessment", "page.assessment.navigation": "Security assessment", "page.assessment.description": "Inspect accepted scanner database revisions and report-archive health; configure Source, Provider, and Controller through governed plugin configuration",
      "panel.catalog": "Artifact catalog", "panel.overview": "Repository overview", "panel.quotas": "Quota usage", "panel.capacity": "Capacity", "panel.references": "Reference snapshots",
      "panel.gc": "Quarantine and sweep records", "panel.gcPlan": "Current GC plan", "panel.migration": "Current migration", "panel.migrationStatus": "Migration status",
      "panel.publications": "Publication requests", "filter.publicationStatus": "Approval status",
      "panel.assessmentRevisions": "Used database revisions", "panel.assessmentOverview": "Assessment evidence status",
      "filter.plugin": "Plugin ID / namespace", "filter.namespace": "Namespace", "filter.publisher": "Publisher", "filter.channel": "Channel", "filter.target": "Target kernel",
      "filter.lifecycle": "Lifecycle", "filter.exceeded": "Exceeded only", "filter.ownerKind": "Owner kind", "filter.gcStatus": "GC status",
      "column.plugin": "Plugin ID", "column.version": "Version", "column.channel": "Channel", "column.publisher": "Publisher", "column.targets": "Target kernels", "column.size": "Size",
      "column.lifecycle": "Lifecycle", "column.sbom": "SBOM", "column.pythonLock": "Python lock", "column.provenance": "Provenance", "column.security": "Security admission", "column.revision": "Repository revision", "column.publishedAt": "Published", "column.quota": "Quota", "column.scope": "Scope",
	  "security.passed": "Rescan passed", "security.failed": "Rescan failed", "security.stale": "Rescan expired", "security.admitted": "Admitted", "security.missing": "Not provided",
      "column.artifacts": "Artifacts", "column.artifactLimit": "Artifact limit", "column.bytes": "Object bytes", "column.byteLimit": "Byte limit", "column.state": "Status",
      "column.tenant": "Tenant", "column.ownerKind": "Owner kind", "column.ownerId": "Owner ID", "column.referencePublisher": "Trusted publisher", "column.generation": "Generation",
      "column.referenceCount": "References", "column.expiresAt": "Lease expiry", "column.gcStatus": "GC status", "column.sweepAfter": "Earliest sweep",
      "column.migrationId": "Migration ID", "column.migrationPhase": "Phase", "column.migrationSource": "Source", "column.migrationTarget": "Target",
      "column.migrationFiles": "Files", "column.migrationBytes": "Synced", "column.migrationDigest": "Sync digest", "column.migrationObservation": "Observation ends", "column.migrationConfigured": "Config switched", "column.migrationError": "Last error",
      "column.publicationStatus": "Approval status", "column.keyId": "Signing key", "column.publicationReason": "Publication reason", "column.submittedBy": "Submitted by", "column.approvedBy": "Approved by", "column.submittedAt": "Submitted", "column.publicationExpiresAt": "Expires", "column.publicationPublishedAt": "Published", "column.publicationTerminalReason": "Terminal reason", "column.publicationTerminalBy": "Terminated by", "column.publicationTerminalAt": "Terminated at",
      "column.databaseRevision": "Database revision", "column.current": "Current", "column.failed": "Failed", "column.stale": "Stale", "column.invalid": "Invalid", "column.lastEvaluatedAt": "Last evaluated",
      "metric.status": "Service status", "metric.activeArtifacts": "Active artifacts", "metric.storedBytes": "Stored bytes", "metric.quota": "Quota status", "metric.security": "Security admission", "metric.provider": "Storage provider",
      "metric.volume": "Active volume", "metric.catalogRevision": "Catalog revision", "metric.migration": "Migration", "metric.activeBytes": "Active bytes",
      "metric.quarantinedBytes": "Quarantined bytes", "metric.reclaimedBytes": "Reclaimed", "metric.gcReady": "Executable", "metric.gcCandidates": "Candidates",
      "metric.gcBytes": "Candidate bytes", "metric.gcBlockers": "Blockers", "metric.migrationPhase": "Current phase", "metric.migrationFiles": "Verified files",
      "metric.migrationBytes": "Verified bytes", "metric.migrationRollback": "Rollback available", "metric.migrationConfiguration": "Runtime config",
      "metric.reportArchive": "Report archive", "metric.databaseRevisions": "Database revisions", "metric.assessmentAlerts": "Assessment alerts", "metric.unassessed": "Unassessed artifacts",
      "action.lifecycle": "Change lifecycle", "action.lifecycle.save": "Apply change", "action.quarantine": "Quarantine current plan", "action.sweep": "Sweep due artifacts",
      "action.migration.prepare": "Prepare migration", "action.migration.sync": "Incremental sync", "action.migration.cutover": "Cut over", "action.migration.rollback": "Roll back",
      "action.migration.finalize": "Finalize", "action.migration.release": "Release old volume",
      "action.publication.submit": "Submit publication", "action.publication.approve": "Approve", "action.publication.reject": "Reject", "action.publication.cancel": "Cancel", "action.evidence": "Supply-chain evidence",
      "action.vulnerabilityReport": "Download vulnerability report", "action.licenseReport": "Download license report",
      "provenance.verified": "Verified", "provenance.missing": "Missing",
      "form.lifecycle.status": "Lifecycle", "form.lifecycle.reason": "Change reason", "form.lifecycle.replacementPlugin": "Replacement plugin ID",
      "form.lifecycle.replacementConstraint": "Replacement version constraint", "form.lifecycle.transition": "Lifecycle transition", "form.lifecycle.replacement": "Deprecation replacement",
      "form.lifecycle.replacementHelp": "Only deprecated artifacts may declare a replacement plugin and SemVer constraint.", "form.lifecycle.title": "Change artifact lifecycle",
      "form.lifecycle.description": "The change is CAS-audited against the Catalog revision; revoked is an irreversible security state.",
      "form.migration.id": "Migration ID", "form.migration.provider": "Target provider", "form.migration.volume": "Target volume", "form.migration.target": "Migration target",
      "form.migration.observation": "Observation period (seconds)", "form.migration.prepareTitle": "Prepare storage migration", "form.migration.prepareDescription": "V1 supports an empty target volume on the same File Provider. Prepare does not switch the active repository.",
      "form.migration.cutoverTitle": "Cut over active volume", "form.migration.cutoverDescription": "The system performs a final incremental sync, atomically switches, and enters dual-write observation.",
      "form.publication.reason": "Publication reason", "form.publication.revision": "Approval revision", "form.publication.title": "Submit stable publication", "form.publication.description": "Approval binds the testing artifact, publisher proof, provenance sidecars, and target stable ref. A different user must approve.",
      "form.publication.rejectReason": "Rejection reason", "form.publication.cancelReason": "Cancellation reason", "form.publication.rejectTitle": "Reject publication", "form.publication.cancelTitle": "Cancel publication", "form.publication.rejectDescription": "Rejection immediately invalidates the stable publication authorization; submitter and rejector separation is enforced.", "form.publication.cancelDescription": "Only the original submitter may cancel. Cancellation is final.",
      "confirm.lifecycle": "Lifecycle changes affect new resolution and delivery. Confirm the reason and replacement are accurate.",
      "confirm.quarantine": "The plan will be regenerated and all candidates quarantined with a 72-hour grace period.", "confirm.sweep": "Only artifacts past their grace period and still unreferenced will be deleted.",
      "confirm.migration.prepare": "The system will probe and bind the target volume. Confirm it is empty and unused.", "confirm.migration.cutover": "Publishing pauses briefly during cutover; reads remain available.",
      "confirm.migration.rollback": "Roll back to the source volume? Observation writes are mirrored and safe to restore.", "confirm.migration.finalize": "End dual-write observation? Rollback is unavailable afterwards.",
      "confirm.migration.release": "Confirm runtime config points to the target volume and release the old volume.",
      "confirm.publication.approve": "Promote this testing artifact to stable? Submitter and approver separation is enforced.",
      "notice.lifecycleSaved": "Artifact lifecycle updated", "notice.migrationPrepared": "Migration prepared", "notice.migrationCutover": "Repository entered observation",
      "notice.publicationSubmitted": "Publication submitted", "notice.publicationApproved": "Publication approved", "notice.publicationRejected": "Publication rejected", "notice.publicationCancelled": "Publication cancelled", "overlay.evidence.title": "Supply-chain evidence", "overlay.evidence.document": "Verified artifact and approval trail",
      "error.lifecycle.replacementPair": "Replacement plugin and version constraint must be provided together", "error.lifecycle.replacementDeprecated": "Only deprecated artifacts may declare a replacement",
      "error.lifecycle.required": "Select a lifecycle and provide a reason", "error.lifecycle.same": "Select a lifecycle different from the current state",
      "lifecycle.active": "Active", "lifecycle.deprecated": "Deprecated", "lifecycle.yanked": "Yanked", "lifecycle.revoked": "Revoked",
      "migration.none": "Not started", "migration.prepared": "Prepared", "migration.synced": "Synced", "migration.observing": "Observing", "migration.finalized": "Finalized", "migration.rolledBack": "Rolled back", "migration.released": "Released",
      "publication.PendingApproval": "Pending approval", "publication.Approved": "Approved", "publication.Published": "Published", "publication.Rejected": "Rejected", "publication.Cancelled": "Cancelled", "publication.Expired": "Expired",
      "sbom.bound": "Bound", "sbom.missing": "Missing",
      "pythonLock.bound": "Closed", "pythonLock.missing": "N/A",
    },
  },
} as const;
