package releaseorchestrator

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	pluginv1 "cdsoft.com.cn/VastPlan/contracts/schemas/plugin/v1"
)

const portalComposerPluginID = "cn.vastplan.platform.configuration.portal-composer"

var capabilityProjectionTargets = []struct {
	path   string
	render func(PluginWorkspace) ([]byte, error)
}{
	{
		path:   "extensions/plugins/cn.vastplan.platform.configuration.portal-composer/portalcomposer/capability_contract.generated.go",
		render: renderPortalComposerGoProjection,
	},
	{
		path:   "core/kernels/frontend-host/src/capabilities/portal-composer-operations.generated.ts",
		render: renderPortalComposerTypeScriptProjection,
	},
}

func SyncCapabilityContractProjections(repositoryRoot string, workspace PluginWorkspace, write bool) ([]DerivedChange, error) {
	var changes []DerivedChange
	for _, target := range capabilityProjectionTargets {
		expected, err := target.render(workspace)
		if err != nil {
			return nil, err
		}
		path := filepath.Join(repositoryRoot, filepath.FromSlash(target.path))
		actual, readErr := os.ReadFile(path)
		if readErr == nil && bytes.Equal(actual, expected) {
			continue
		}
		if readErr != nil && !errors.Is(readErr, os.ErrNotExist) {
			return nil, readErr
		}
		changes = append(changes, DerivedChange{Path: target.path, Reason: "signed capability contract projection"})
		if write {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return nil, err
			}
			if err := os.WriteFile(path, expected, 0o644); err != nil {
				return nil, err
			}
		}
	}
	return changes, nil
}

func renderPortalComposerGoProjection(workspace PluginWorkspace) ([]byte, error) {
	plugin, ok := workspace.Plugins[portalComposerPluginID]
	if !ok {
		return nil, fmt.Errorf("Capability Contract 投影引用不存在的插件 %s", portalComposerPluginID)
	}
	contributions, err := pluginv1.BackendRuntimeContributions(plugin.Manifest)
	if err != nil {
		return nil, err
	}
	descriptors := map[string]string{}
	for _, contribution := range contributions {
		if contribution.ExtensionPoint == "tool.package" {
			descriptors[contribution.ID] = string(contribution.Descriptor)
		}
	}
	ids := make([]string, 0, len(descriptors))
	for id := range descriptors {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	contracts, err := pluginv1.ManifestToolCapabilityContracts(plugin.Manifest)
	if err != nil {
		return nil, err
	}
	operations := make(map[string][]string, len(contracts))
	for _, contract := range contracts {
		for _, operation := range contract.Operations {
			operations[contract.Capability] = append(operations[contract.Capability], operation.Name)
		}
	}
	var out strings.Builder
	out.WriteString("// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.\n\npackage portalcomposer\n\n")
	fmt.Fprintf(&out, "const (\n\tPluginID = %s\n\tPluginVersion = %s\n)\n\n", strconv.Quote(plugin.ID), strconv.Quote(plugin.Version))
	out.WriteString("var signedToolDescriptors = map[string]string{\n")
	for _, id := range ids {
		fmt.Fprintf(&out, "\t%s: %s,\n", strconv.Quote(id), strconv.Quote(descriptors[id]))
	}
	out.WriteString("}\n\nvar signedToolOperations = map[string][]string{\n")
	for _, id := range ids {
		fmt.Fprintf(&out, "\t%s: {", strconv.Quote(id))
		for index, operation := range operations[id] {
			if index > 0 {
				out.WriteString(", ")
			}
			out.WriteString(strconv.Quote(operation))
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n\nfunc signedToolDescriptor(capability string) []byte {\n\traw, ok := signedToolDescriptors[capability]\n\tif !ok {\n\t\tpanic(\"未生成签名 Tool Capability Contract: \" + capability)\n\t}\n\treturn []byte(raw)\n}\n\n")
	out.WriteString("func signedToolOperationNames(capability string) []string {\n\toperations, ok := signedToolOperations[capability]\n\tif !ok {\n\t\tpanic(\"未生成签名 Tool operations: \" + capability)\n\t}\n\treturn append([]string(nil), operations...)\n}\n")
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("格式化 Portal Composer Go Capability 投影: %w", err)
	}
	return formatted, nil
}

func renderPortalComposerTypeScriptProjection(workspace PluginWorkspace) ([]byte, error) {
	plugin, ok := workspace.Plugins[portalComposerPluginID]
	if !ok {
		return nil, fmt.Errorf("Capability Contract 投影引用不存在的插件 %s", portalComposerPluginID)
	}
	contracts, err := pluginv1.ManifestToolCapabilityContracts(plugin.Manifest)
	if err != nil {
		return nil, err
	}
	var composer *pluginv1.ToolCapabilityContract
	for index := range contracts {
		if contracts[index].Capability == "platform.portal-composer" {
			composer = &contracts[index]
			break
		}
	}
	if composer == nil {
		return nil, errors.New("Portal Composer Manifest 缺少 platform.portal-composer Tool Capability Contract")
	}
	var out strings.Builder
	out.WriteString("// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.\n")
	out.WriteString("export const portalComposerOperations = Object.freeze([\n")
	for _, operation := range composer.Operations {
		fmt.Fprintf(&out, "  %s,\n", strconv.Quote(operation.Name))
	}
	out.WriteString("] as const);\n\nexport type PortalComposerOperation = (typeof portalComposerOperations)[number];\n\n")
	out.WriteString("export const portalComposerOperationSet: ReadonlySet<string> = new Set(portalComposerOperations);\n")
	return []byte(out.String()), nil
}
