package releaseorchestrator

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

var foundationCatalogTargets = []struct {
	path   string
	render func(PluginWorkspace) ([]byte, error)
}{
	{
		path: "extensions/plugins/cn.vastplan.foundation.frontend.render.adapter/frontend/src/renderer-versions.generated.ts",
		render: func(workspace PluginWorkspace) ([]byte, error) {
			antd, err := workspaceVersion(workspace, "cn.vastplan.foundation.frontend.render.adapter.antd")
			if err != nil {
				return nil, err
			}
			return []byte(fmt.Sprintf("// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.\nexport const rendererPluginVersions = Object.freeze({\n  antd: %q,\n} as const);\n", antd)), nil
		},
	},
	{
		path: "extensions/plugins/cn.vastplan.foundation.frontend.structure.shell/frontend/src/template-versions.generated.ts",
		render: func(workspace PluginWorkspace) ([]byte, error) {
			standard, err := workspaceVersion(workspace, "cn.vastplan.foundation.frontend.structure.layout.standard")
			if err != nil {
				return nil, err
			}
			top, err := workspaceVersion(workspace, "cn.vastplan.foundation.frontend.structure.layout.top-navigation")
			if err != nil {
				return nil, err
			}
			return []byte(fmt.Sprintf("// Code generated by engineering/tools/pluginrelease prepare; DO NOT EDIT.\nexport const shellLibraryPluginVersions = Object.freeze({\n  standard: %q,\n  topNavigation: %q,\n} as const);\n", standard, top)), nil
		},
	},
}

func SyncFoundationCatalogVersions(repositoryRoot string, workspace PluginWorkspace, write bool) ([]DerivedChange, error) {
	if len(workspace.Plugins) == 0 {
		return nil, errors.New("生成 Foundation Catalog 版本缺少插件工作区")
	}
	var changes []DerivedChange
	for _, target := range foundationCatalogTargets {
		expected, err := target.render(workspace)
		if err != nil {
			return nil, err
		}
		path := filepath.Join(repositoryRoot, filepath.FromSlash(target.path))
		actual, readErr := os.ReadFile(path)
		if readErr == nil && bytes.Equal(actual, expected) {
			continue
		}
		if readErr != nil && !errors.Is(readErr, os.ErrNotExist) {
			return nil, readErr
		}
		changes = append(changes, DerivedChange{Path: target.path, Reason: "plugin manifest exact version"})
		if write {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return nil, err
			}
			if err := os.WriteFile(path, expected, 0o644); err != nil {
				return nil, err
			}
		}
	}
	return changes, nil
}

func workspaceVersion(workspace PluginWorkspace, pluginID string) (string, error) {
	plugin, ok := workspace.Plugins[pluginID]
	if !ok {
		return "", fmt.Errorf("Foundation Catalog 引用不存在的插件 %s", pluginID)
	}
	return plugin.Version, nil
}
