// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pluginhost/v1/pluginhost.proto

// 插件-宿主协议（Plugin-Host Protocol）——内核内：宿主 ↔ 本内核插件
// 规格见 docs/dev/architecture/插件契约与协议.md 第二章
//
// 方向：**宿主是 gRPC 服务端，插件是客户端**。宿主拉起插件时注入连接端点，
// 插件回连并主动 Hello（第二章 §2.2）。这样插件→宿主的回调是天然的，
// 宿主→插件的调用则经 Channel 双向流下发。

package pluginhostv1

import (
	v1 "cdsoft.com.cn/VastPlan/core/shared/go/contract/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lifecycle_Op int32

const (
	Lifecycle_OP_UNSPECIFIED Lifecycle_Op = 0
	Lifecycle_OP_ACTIVATE    Lifecycle_Op = 1
	Lifecycle_OP_DEACTIVATE  Lifecycle_Op = 2
	Lifecycle_OP_DRAIN       Lifecycle_Op = 3
	Lifecycle_OP_SHUTDOWN    Lifecycle_Op = 4
	// 有状态升级采用 copy-on-write 三阶段事务。PREPARE/COMMIT 后、候选取得
	// 路由所有权前仍必须支持 ROLLBACK；旧实例始终读取旧状态视图。
	Lifecycle_OP_MIGRATION_PREPARE  Lifecycle_Op = 5
	Lifecycle_OP_MIGRATION_COMMIT   Lifecycle_Op = 6
	Lifecycle_OP_MIGRATION_ROLLBACK Lifecycle_Op = 7
)

// Enum value maps for Lifecycle_Op.
var (
	Lifecycle_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_ACTIVATE",
		2: "OP_DEACTIVATE",
		3: "OP_DRAIN",
		4: "OP_SHUTDOWN",
		5: "OP_MIGRATION_PREPARE",
		6: "OP_MIGRATION_COMMIT",
		7: "OP_MIGRATION_ROLLBACK",
	}
	Lifecycle_Op_value = map[string]int32{
		"OP_UNSPECIFIED":        0,
		"OP_ACTIVATE":           1,
		"OP_DEACTIVATE":         2,
		"OP_DRAIN":              3,
		"OP_SHUTDOWN":           4,
		"OP_MIGRATION_PREPARE":  5,
		"OP_MIGRATION_COMMIT":   6,
		"OP_MIGRATION_ROLLBACK": 7,
	}
)

func (x Lifecycle_Op) Enum() *Lifecycle_Op {
	p := new(Lifecycle_Op)
	*p = x
	return p
}

func (x Lifecycle_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_pluginhost_v1_pluginhost_proto_enumTypes[0].Descriptor()
}

func (Lifecycle_Op) Type() protoreflect.EnumType {
	return &file_pluginhost_v1_pluginhost_proto_enumTypes[0]
}

func (x Lifecycle_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle_Op.Descriptor instead.
func (Lifecycle_Op) EnumDescriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{12, 0}
}

// 插件→宿主：自报身份、版本集与 engines 兼容声明。
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoVersions []int32                `protobuf:"varint,1,rep,packed,name=proto_versions,json=protoVersions,proto3" json:"proto_versions,omitempty"` // 插件支持的协议版本集
	Magic         string                 `protobuf:"bytes,2,opt,name=magic,proto3" json:"magic,omitempty"`                                              // magic cookie，防误把普通进程当插件
	PluginId      string                 `protobuf:"bytes,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion string                 `protobuf:"bytes,4,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// 清单 engines：{内核规范ID: SemVer 范围}，如 {"backend": "^0.1"}。
	// 宿主用它校验自身版本是否满足（ADR-0017 §4 强制点 2）；
	// 未声明本内核 → fail-closed 拒绝装载。
	Engines map[string]string `protobuf:"bytes,5,rep,name=engines,proto3" json:"engines,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 宿主拉起插件时注入的一次性令牌，用于把本次握手对应回那次 Launch。
	LaunchToken string `protobuf:"bytes,6,opt,name=launch_token,json=launchToken,proto3" json:"launch_token,omitempty"`
	// 可选协议能力。旧客户端不发送；宿主只返回双方交集。
	Features      []string `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtoVersions() []int32 {
	if x != nil {
		return x.ProtoVersions
	}
	return nil
}

func (x *Hello) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *Hello) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Hello) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *Hello) GetEngines() map[string]string {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *Hello) GetLaunchToken() string {
	if x != nil {
		return x.LaunchToken
	}
	return ""
}

func (x *Hello) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// 宿主→插件：协商结果 + 会话票据。
type HelloAck struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NegotiatedProto    int32                  `protobuf:"varint,1,opt,name=negotiated_proto,json=negotiatedProto,proto3" json:"negotiated_proto,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 宿主签发的会话票据：审计与回调鉴权
	HostCapabilities   []string               `protobuf:"bytes,3,rep,name=host_capabilities,json=hostCapabilities,proto3" json:"host_capabilities,omitempty"`
	NegotiatedFeatures []string               `protobuf:"bytes,4,rep,name=negotiated_features,json=negotiatedFeatures,proto3" json:"negotiated_features,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetNegotiatedProto() int32 {
	if x != nil {
		return x.NegotiatedProto
	}
	return 0
}

func (x *HelloAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloAck) GetHostCapabilities() []string {
	if x != nil {
		return x.HostCapabilities
	}
	return nil
}

func (x *HelloAck) GetNegotiatedFeatures() []string {
	if x != nil {
		return x.NegotiatedFeatures
	}
	return nil
}

type Contribution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtensionPoint string                 `protobuf:"bytes,1,opt,name=extension_point,json=extensionPoint,proto3" json:"extension_point,omitempty"` // 目标 Registry 名（= CallTarget.extension_point）
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                               // 贡献稳定逻辑名（= CallTarget.capability），四处同名
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// 该扩展点要求的贡献契约（JSON，见第四章）。
	// 命名带 _json 后缀以避开 protobuf 生成的 Descriptor() 方法冲突。
	DescriptorJson []byte `protobuf:"bytes,4,opt,name=descriptor_json,json=descriptorJson,proto3" json:"descriptor_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contribution) Reset() {
	*x = Contribution{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contribution) ProtoMessage() {}

func (x *Contribution) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contribution.ProtoReflect.Descriptor instead.
func (*Contribution) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{2}
}

func (x *Contribution) GetExtensionPoint() string {
	if x != nil {
		return x.ExtensionPoint
	}
	return ""
}

func (x *Contribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contribution) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Contribution) GetDescriptorJson() []byte {
	if x != nil {
		return x.DescriptorJson
	}
	return nil
}

// 插件声明它填充哪些扩展点（Channel 上的首条消息）。
type Declaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contributions []*Contribution        `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Declaration) Reset() {
	*x = Declaration{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Declaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Declaration) ProtoMessage() {}

func (x *Declaration) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Declaration.ProtoReflect.Descriptor instead.
func (*Declaration) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{3}
}

func (x *Declaration) GetContributions() []*Contribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

// 宿主逐条接受/拒绝（非法者 fail-closed）。
type Registered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      []string               `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      map[string]string      `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // id -> 原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{4}
}

func (x *Registered) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *Registered) GetRejected() map[string]string {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type ContributionRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtensionPoint string                 `protobuf:"bytes,1,opt,name=extension_point,json=extensionPoint,proto3" json:"extension_point,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContributionRef) Reset() {
	*x = ContributionRef{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionRef) ProtoMessage() {}

func (x *ContributionRef) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionRef.ProtoReflect.Descriptor instead.
func (*ContributionRef) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{5}
}

func (x *ContributionRef) GetExtensionPoint() string {
	if x != nil {
		return x.ExtensionPoint
	}
	return ""
}

func (x *ContributionRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterContributions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Contributions []*Contribution        `protobuf:"bytes,2,rep,name=contributions,proto3" json:"contributions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContributions) Reset() {
	*x = RegisterContributions{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContributions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContributions) ProtoMessage() {}

func (x *RegisterContributions) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContributions.ProtoReflect.Descriptor instead.
func (*RegisterContributions) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterContributions) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RegisterContributions) GetContributions() []*Contribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

type UnregisterContributions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Contributions []*ContributionRef     `protobuf:"bytes,2,rep,name=contributions,proto3" json:"contributions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterContributions) Reset() {
	*x = UnregisterContributions{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterContributions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterContributions) ProtoMessage() {}

func (x *UnregisterContributions) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterContributions.ProtoReflect.Descriptor instead.
func (*UnregisterContributions) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterContributions) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnregisterContributions) GetContributions() []*ContributionRef {
	if x != nil {
		return x.Contributions
	}
	return nil
}

type ContributionUpdateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accepted      []string               `protobuf:"bytes,2,rep,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      map[string]string      `protobuf:"bytes,3,rep,name=rejected,proto3" json:"rejected,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionUpdateAck) Reset() {
	*x = ContributionUpdateAck{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionUpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionUpdateAck) ProtoMessage() {}

func (x *ContributionUpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionUpdateAck.ProtoReflect.Descriptor instead.
func (*ContributionUpdateAck) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{8}
}

func (x *ContributionUpdateAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ContributionUpdateAck) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *ContributionUpdateAck) GetRejected() map[string]string {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type InvokeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 双向流上关联请求与响应
	Target    *v1.CallTarget         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Context   *v1.CallContext        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Payload   []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// 宿主签发、仅限当前插件会话与当前调用生命周期使用的 opaque 委托引用。
	// 它是协议控制信息，不属于可透传的 CallContext baggage。
	DelegationToken *string `protobuf:"bytes,5,opt,name=delegation_token,json=delegationToken,proto3,oneof" json:"delegation_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeRequest) GetTarget() *v1.CallTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InvokeRequest) GetContext() *v1.CallContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetDelegationToken() string {
	if x != nil && x.DelegationToken != nil {
		return *x.DelegationToken
	}
	return ""
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result        *v1.CallResult         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{10}
}

func (x *InvokeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeResponse) GetResult() *v1.CallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.CallEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{11}
}

func (x *EventEnvelope) GetEvent() *v1.CallEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type Lifecycle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Op               Lifecycle_Op           `protobuf:"varint,2,opt,name=op,proto3,enum=vastplan.pluginhost.v1.Lifecycle_Op" json:"op,omitempty"`
	TransactionId    string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FromStateFormat  string                 `protobuf:"bytes,4,opt,name=from_state_format,json=fromStateFormat,proto3" json:"from_state_format,omitempty"`
	FromStateVersion int32                  `protobuf:"varint,5,opt,name=from_state_version,json=fromStateVersion,proto3" json:"from_state_version,omitempty"`
	ToStateFormat    string                 `protobuf:"bytes,6,opt,name=to_state_format,json=toStateFormat,proto3" json:"to_state_format,omitempty"`
	ToStateVersion   int32                  `protobuf:"varint,7,opt,name=to_state_version,json=toStateVersion,proto3" json:"to_state_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lifecycle) Reset() {
	*x = Lifecycle{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifecycle) ProtoMessage() {}

func (x *Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifecycle.ProtoReflect.Descriptor instead.
func (*Lifecycle) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{12}
}

func (x *Lifecycle) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Lifecycle) GetOp() Lifecycle_Op {
	if x != nil {
		return x.Op
	}
	return Lifecycle_OP_UNSPECIFIED
}

func (x *Lifecycle) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Lifecycle) GetFromStateFormat() string {
	if x != nil {
		return x.FromStateFormat
	}
	return ""
}

func (x *Lifecycle) GetFromStateVersion() int32 {
	if x != nil {
		return x.FromStateVersion
	}
	return 0
}

func (x *Lifecycle) GetToStateFormat() string {
	if x != nil {
		return x.ToStateFormat
	}
	return ""
}

func (x *Lifecycle) GetToStateVersion() int32 {
	if x != nil {
		return x.ToStateVersion
	}
	return 0
}

type LifecycleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleAck) Reset() {
	*x = LifecycleAck{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleAck) ProtoMessage() {}

func (x *LifecycleAck) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleAck.ProtoReflect.Descriptor instead.
func (*LifecycleAck) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{13}
}

func (x *LifecycleAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LifecycleAck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *LifecycleAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{14}
}

func (x *Ping) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{15}
}

func (x *Pong) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Cancel 取消同一 Channel 上尚未完成的 Invoke/HostCall。重复或迟到取消幂等忽略。
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{16}
}

func (x *Cancel) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Cancel) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type FromPlugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*FromPlugin_Declare
	//	*FromPlugin_InvokeResult
	//	*FromPlugin_HostCall
	//	*FromPlugin_Event
	//	*FromPlugin_LifecycleAck
	//	*FromPlugin_Pong
	//	*FromPlugin_Register
	//	*FromPlugin_Unregister
	//	*FromPlugin_Cancel
	Msg           isFromPlugin_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromPlugin) Reset() {
	*x = FromPlugin{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromPlugin) ProtoMessage() {}

func (x *FromPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromPlugin.ProtoReflect.Descriptor instead.
func (*FromPlugin) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{17}
}

func (x *FromPlugin) GetMsg() isFromPlugin_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *FromPlugin) GetDeclare() *Declaration {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_Declare); ok {
			return x.Declare
		}
	}
	return nil
}

func (x *FromPlugin) GetInvokeResult() *InvokeResponse {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_InvokeResult); ok {
			return x.InvokeResult
		}
	}
	return nil
}

func (x *FromPlugin) GetHostCall() *InvokeRequest {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_HostCall); ok {
			return x.HostCall
		}
	}
	return nil
}

func (x *FromPlugin) GetEvent() *EventEnvelope {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *FromPlugin) GetLifecycleAck() *LifecycleAck {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_LifecycleAck); ok {
			return x.LifecycleAck
		}
	}
	return nil
}

func (x *FromPlugin) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *FromPlugin) GetRegister() *RegisterContributions {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *FromPlugin) GetUnregister() *UnregisterContributions {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_Unregister); ok {
			return x.Unregister
		}
	}
	return nil
}

func (x *FromPlugin) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Msg.(*FromPlugin_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isFromPlugin_Msg interface {
	isFromPlugin_Msg()
}

type FromPlugin_Declare struct {
	Declare *Declaration `protobuf:"bytes,1,opt,name=declare,proto3,oneof"`
}

type FromPlugin_InvokeResult struct {
	InvokeResult *InvokeResponse `protobuf:"bytes,2,opt,name=invoke_result,json=invokeResult,proto3,oneof"` // 回应宿主的 Invoke
}

type FromPlugin_HostCall struct {
	HostCall *InvokeRequest `protobuf:"bytes,3,opt,name=host_call,json=hostCall,proto3,oneof"` // 回调宿主内核服务 / 经寻址层调别的能力
}

type FromPlugin_Event struct {
	Event *EventEnvelope `protobuf:"bytes,4,opt,name=event,proto3,oneof"` // 发布事件
}

type FromPlugin_LifecycleAck struct {
	LifecycleAck *LifecycleAck `protobuf:"bytes,5,opt,name=lifecycle_ack,json=lifecycleAck,proto3,oneof"`
}

type FromPlugin_Pong struct {
	Pong *Pong `protobuf:"bytes,6,opt,name=pong,proto3,oneof"`
}

type FromPlugin_Register struct {
	Register *RegisterContributions `protobuf:"bytes,7,opt,name=register,proto3,oneof"`
}

type FromPlugin_Unregister struct {
	Unregister *UnregisterContributions `protobuf:"bytes,8,opt,name=unregister,proto3,oneof"`
}

type FromPlugin_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,9,opt,name=cancel,proto3,oneof"`
}

func (*FromPlugin_Declare) isFromPlugin_Msg() {}

func (*FromPlugin_InvokeResult) isFromPlugin_Msg() {}

func (*FromPlugin_HostCall) isFromPlugin_Msg() {}

func (*FromPlugin_Event) isFromPlugin_Msg() {}

func (*FromPlugin_LifecycleAck) isFromPlugin_Msg() {}

func (*FromPlugin_Pong) isFromPlugin_Msg() {}

func (*FromPlugin_Register) isFromPlugin_Msg() {}

func (*FromPlugin_Unregister) isFromPlugin_Msg() {}

func (*FromPlugin_Cancel) isFromPlugin_Msg() {}

type FromHost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*FromHost_Registered
	//	*FromHost_Invoke
	//	*FromHost_HostCallResult
	//	*FromHost_Event
	//	*FromHost_Lifecycle
	//	*FromHost_Ping
	//	*FromHost_ContributionUpdateAck
	//	*FromHost_Cancel
	Msg           isFromHost_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromHost) Reset() {
	*x = FromHost{}
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromHost) ProtoMessage() {}

func (x *FromHost) ProtoReflect() protoreflect.Message {
	mi := &file_pluginhost_v1_pluginhost_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromHost.ProtoReflect.Descriptor instead.
func (*FromHost) Descriptor() ([]byte, []int) {
	return file_pluginhost_v1_pluginhost_proto_rawDescGZIP(), []int{18}
}

func (x *FromHost) GetMsg() isFromHost_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *FromHost) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *FromHost) GetInvoke() *InvokeRequest {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

func (x *FromHost) GetHostCallResult() *InvokeResponse {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_HostCallResult); ok {
			return x.HostCallResult
		}
	}
	return nil
}

func (x *FromHost) GetEvent() *EventEnvelope {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *FromHost) GetLifecycle() *Lifecycle {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_Lifecycle); ok {
			return x.Lifecycle
		}
	}
	return nil
}

func (x *FromHost) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *FromHost) GetContributionUpdateAck() *ContributionUpdateAck {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_ContributionUpdateAck); ok {
			return x.ContributionUpdateAck
		}
	}
	return nil
}

func (x *FromHost) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Msg.(*FromHost_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isFromHost_Msg interface {
	isFromHost_Msg()
}

type FromHost_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type FromHost_Invoke struct {
	Invoke *InvokeRequest `protobuf:"bytes,2,opt,name=invoke,proto3,oneof"` // 触发扩展点
}

type FromHost_HostCallResult struct {
	HostCallResult *InvokeResponse `protobuf:"bytes,3,opt,name=host_call_result,json=hostCallResult,proto3,oneof"` // 回应插件的 HostCall
}

type FromHost_Event struct {
	Event *EventEnvelope `protobuf:"bytes,4,opt,name=event,proto3,oneof"` // 下发事件
}

type FromHost_Lifecycle struct {
	Lifecycle *Lifecycle `protobuf:"bytes,5,opt,name=lifecycle,proto3,oneof"`
}

type FromHost_Ping struct {
	Ping *Ping `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

type FromHost_ContributionUpdateAck struct {
	ContributionUpdateAck *ContributionUpdateAck `protobuf:"bytes,7,opt,name=contribution_update_ack,json=contributionUpdateAck,proto3,oneof"`
}

type FromHost_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,8,opt,name=cancel,proto3,oneof"`
}

func (*FromHost_Registered) isFromHost_Msg() {}

func (*FromHost_Invoke) isFromHost_Msg() {}

func (*FromHost_HostCallResult) isFromHost_Msg() {}

func (*FromHost_Event) isFromHost_Msg() {}

func (*FromHost_Lifecycle) isFromHost_Msg() {}

func (*FromHost_Ping) isFromHost_Msg() {}

func (*FromHost_ContributionUpdateAck) isFromHost_Msg() {}

func (*FromHost_Cancel) isFromHost_Msg() {}

var File_pluginhost_v1_pluginhost_proto protoreflect.FileDescriptor

const file_pluginhost_v1_pluginhost_proto_rawDesc = "" +
	"\n" +
	"\x1epluginhost/v1/pluginhost.proto\x12\x16vastplan.pluginhost.v1\x1a\x1acontract/v1/contract.proto\"\xc9\x02\n" +
	"\x05Hello\x12%\n" +
	"\x0eproto_versions\x18\x01 \x03(\x05R\rprotoVersions\x12\x14\n" +
	"\x05magic\x18\x02 \x01(\tR\x05magic\x12\x1b\n" +
	"\tplugin_id\x18\x03 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x04 \x01(\tR\rpluginVersion\x12D\n" +
	"\aengines\x18\x05 \x03(\v2*.vastplan.pluginhost.v1.Hello.EnginesEntryR\aengines\x12!\n" +
	"\flaunch_token\x18\x06 \x01(\tR\vlaunchToken\x12\x1a\n" +
	"\bfeatures\x18\a \x03(\tR\bfeatures\x1a:\n" +
	"\fEnginesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\bHelloAck\x12)\n" +
	"\x10negotiated_proto\x18\x01 \x01(\x05R\x0fnegotiatedProto\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12+\n" +
	"\x11host_capabilities\x18\x03 \x03(\tR\x10hostCapabilities\x12/\n" +
	"\x13negotiated_features\x18\x04 \x03(\tR\x12negotiatedFeatures\"\x8c\x01\n" +
	"\fContribution\x12'\n" +
	"\x0fextension_point\x18\x01 \x01(\tR\x0eextensionPoint\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12'\n" +
	"\x0fdescriptor_json\x18\x04 \x01(\fR\x0edescriptorJson\"Y\n" +
	"\vDeclaration\x12J\n" +
	"\rcontributions\x18\x01 \x03(\v2$.vastplan.pluginhost.v1.ContributionR\rcontributions\"\xb3\x01\n" +
	"\n" +
	"Registered\x12\x1a\n" +
	"\baccepted\x18\x01 \x03(\tR\baccepted\x12L\n" +
	"\brejected\x18\x02 \x03(\v20.vastplan.pluginhost.v1.Registered.RejectedEntryR\brejected\x1a;\n" +
	"\rRejectedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x0fContributionRef\x12'\n" +
	"\x0fextension_point\x18\x01 \x01(\tR\x0eextensionPoint\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x82\x01\n" +
	"\x15RegisterContributions\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12J\n" +
	"\rcontributions\x18\x02 \x03(\v2$.vastplan.pluginhost.v1.ContributionR\rcontributions\"\x87\x01\n" +
	"\x17UnregisterContributions\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12M\n" +
	"\rcontributions\x18\x02 \x03(\v2'.vastplan.pluginhost.v1.ContributionRefR\rcontributions\"\xe8\x01\n" +
	"\x15ContributionUpdateAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\baccepted\x18\x02 \x03(\tR\baccepted\x12W\n" +
	"\brejected\x18\x03 \x03(\v2;.vastplan.pluginhost.v1.ContributionUpdateAck.RejectedEntryR\brejected\x1a;\n" +
	"\rRejectedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06target\x18\x02 \x01(\v2 .vastplan.contract.v1.CallTargetR\x06target\x12;\n" +
	"\acontext\x18\x03 \x01(\v2!.vastplan.contract.v1.CallContextR\acontext\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12.\n" +
	"\x10delegation_token\x18\x05 \x01(\tH\x00R\x0fdelegationToken\x88\x01\x01B\x13\n" +
	"\x11_delegation_token\"\x83\x01\n" +
	"\x0eInvokeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06result\x18\x02 \x01(\v2 .vastplan.contract.v1.CallResultR\x06result\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"F\n" +
	"\rEventEnvelope\x125\n" +
	"\x05event\x18\x01 \x01(\v2\x1f.vastplan.contract.v1.CallEventR\x05event\"\xdf\x03\n" +
	"\tLifecycle\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x124\n" +
	"\x02op\x18\x02 \x01(\x0e2$.vastplan.pluginhost.v1.Lifecycle.OpR\x02op\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12*\n" +
	"\x11from_state_format\x18\x04 \x01(\tR\x0ffromStateFormat\x12,\n" +
	"\x12from_state_version\x18\x05 \x01(\x05R\x10fromStateVersion\x12&\n" +
	"\x0fto_state_format\x18\x06 \x01(\tR\rtoStateFormat\x12(\n" +
	"\x10to_state_version\x18\a \x01(\x05R\x0etoStateVersion\"\xa9\x01\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOP_ACTIVATE\x10\x01\x12\x11\n" +
	"\rOP_DEACTIVATE\x10\x02\x12\f\n" +
	"\bOP_DRAIN\x10\x03\x12\x0f\n" +
	"\vOP_SHUTDOWN\x10\x04\x12\x18\n" +
	"\x14OP_MIGRATION_PREPARE\x10\x05\x12\x17\n" +
	"\x13OP_MIGRATION_COMMIT\x10\x06\x12\x19\n" +
	"\x15OP_MIGRATION_ROLLBACK\x10\a\"n\n" +
	"\fLifecycleAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"%\n" +
	"\x04Ping\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"%\n" +
	"\x04Pong\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"O\n" +
	"\x06Cancel\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\x83\x05\n" +
	"\n" +
	"FromPlugin\x12?\n" +
	"\adeclare\x18\x01 \x01(\v2#.vastplan.pluginhost.v1.DeclarationH\x00R\adeclare\x12M\n" +
	"\rinvoke_result\x18\x02 \x01(\v2&.vastplan.pluginhost.v1.InvokeResponseH\x00R\finvokeResult\x12D\n" +
	"\thost_call\x18\x03 \x01(\v2%.vastplan.pluginhost.v1.InvokeRequestH\x00R\bhostCall\x12=\n" +
	"\x05event\x18\x04 \x01(\v2%.vastplan.pluginhost.v1.EventEnvelopeH\x00R\x05event\x12K\n" +
	"\rlifecycle_ack\x18\x05 \x01(\v2$.vastplan.pluginhost.v1.LifecycleAckH\x00R\flifecycleAck\x122\n" +
	"\x04pong\x18\x06 \x01(\v2\x1c.vastplan.pluginhost.v1.PongH\x00R\x04pong\x12K\n" +
	"\bregister\x18\a \x01(\v2-.vastplan.pluginhost.v1.RegisterContributionsH\x00R\bregister\x12Q\n" +
	"\n" +
	"unregister\x18\b \x01(\v2/.vastplan.pluginhost.v1.UnregisterContributionsH\x00R\n" +
	"unregister\x128\n" +
	"\x06cancel\x18\t \x01(\v2\x1e.vastplan.pluginhost.v1.CancelH\x00R\x06cancelB\x05\n" +
	"\x03msg\"\xc5\x04\n" +
	"\bFromHost\x12D\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\".vastplan.pluginhost.v1.RegisteredH\x00R\n" +
	"registered\x12?\n" +
	"\x06invoke\x18\x02 \x01(\v2%.vastplan.pluginhost.v1.InvokeRequestH\x00R\x06invoke\x12R\n" +
	"\x10host_call_result\x18\x03 \x01(\v2&.vastplan.pluginhost.v1.InvokeResponseH\x00R\x0ehostCallResult\x12=\n" +
	"\x05event\x18\x04 \x01(\v2%.vastplan.pluginhost.v1.EventEnvelopeH\x00R\x05event\x12A\n" +
	"\tlifecycle\x18\x05 \x01(\v2!.vastplan.pluginhost.v1.LifecycleH\x00R\tlifecycle\x122\n" +
	"\x04ping\x18\x06 \x01(\v2\x1c.vastplan.pluginhost.v1.PingH\x00R\x04ping\x12g\n" +
	"\x17contribution_update_ack\x18\a \x01(\v2-.vastplan.pluginhost.v1.ContributionUpdateAckH\x00R\x15contributionUpdateAck\x128\n" +
	"\x06cancel\x18\b \x01(\v2\x1e.vastplan.pluginhost.v1.CancelH\x00R\x06cancelB\x05\n" +
	"\x03msg2\xaf\x01\n" +
	"\n" +
	"PluginHost\x12L\n" +
	"\tHandshake\x12\x1d.vastplan.pluginhost.v1.Hello\x1a .vastplan.pluginhost.v1.HelloAck\x12S\n" +
	"\aChannel\x12\".vastplan.pluginhost.v1.FromPlugin\x1a .vastplan.pluginhost.v1.FromHost(\x010\x01BBZ@cdsoft.com.cn/VastPlan/core/shared/go/pluginhost/v1;pluginhostv1b\x06proto3"

var (
	file_pluginhost_v1_pluginhost_proto_rawDescOnce sync.Once
	file_pluginhost_v1_pluginhost_proto_rawDescData []byte
)

func file_pluginhost_v1_pluginhost_proto_rawDescGZIP() []byte {
	file_pluginhost_v1_pluginhost_proto_rawDescOnce.Do(func() {
		file_pluginhost_v1_pluginhost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginhost_v1_pluginhost_proto_rawDesc), len(file_pluginhost_v1_pluginhost_proto_rawDesc)))
	})
	return file_pluginhost_v1_pluginhost_proto_rawDescData
}

var file_pluginhost_v1_pluginhost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pluginhost_v1_pluginhost_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pluginhost_v1_pluginhost_proto_goTypes = []any{
	(Lifecycle_Op)(0),               // 0: vastplan.pluginhost.v1.Lifecycle.Op
	(*Hello)(nil),                   // 1: vastplan.pluginhost.v1.Hello
	(*HelloAck)(nil),                // 2: vastplan.pluginhost.v1.HelloAck
	(*Contribution)(nil),            // 3: vastplan.pluginhost.v1.Contribution
	(*Declaration)(nil),             // 4: vastplan.pluginhost.v1.Declaration
	(*Registered)(nil),              // 5: vastplan.pluginhost.v1.Registered
	(*ContributionRef)(nil),         // 6: vastplan.pluginhost.v1.ContributionRef
	(*RegisterContributions)(nil),   // 7: vastplan.pluginhost.v1.RegisterContributions
	(*UnregisterContributions)(nil), // 8: vastplan.pluginhost.v1.UnregisterContributions
	(*ContributionUpdateAck)(nil),   // 9: vastplan.pluginhost.v1.ContributionUpdateAck
	(*InvokeRequest)(nil),           // 10: vastplan.pluginhost.v1.InvokeRequest
	(*InvokeResponse)(nil),          // 11: vastplan.pluginhost.v1.InvokeResponse
	(*EventEnvelope)(nil),           // 12: vastplan.pluginhost.v1.EventEnvelope
	(*Lifecycle)(nil),               // 13: vastplan.pluginhost.v1.Lifecycle
	(*LifecycleAck)(nil),            // 14: vastplan.pluginhost.v1.LifecycleAck
	(*Ping)(nil),                    // 15: vastplan.pluginhost.v1.Ping
	(*Pong)(nil),                    // 16: vastplan.pluginhost.v1.Pong
	(*Cancel)(nil),                  // 17: vastplan.pluginhost.v1.Cancel
	(*FromPlugin)(nil),              // 18: vastplan.pluginhost.v1.FromPlugin
	(*FromHost)(nil),                // 19: vastplan.pluginhost.v1.FromHost
	nil,                             // 20: vastplan.pluginhost.v1.Hello.EnginesEntry
	nil,                             // 21: vastplan.pluginhost.v1.Registered.RejectedEntry
	nil,                             // 22: vastplan.pluginhost.v1.ContributionUpdateAck.RejectedEntry
	(*v1.CallTarget)(nil),           // 23: vastplan.contract.v1.CallTarget
	(*v1.CallContext)(nil),          // 24: vastplan.contract.v1.CallContext
	(*v1.CallResult)(nil),           // 25: vastplan.contract.v1.CallResult
	(*v1.CallEvent)(nil),            // 26: vastplan.contract.v1.CallEvent
}
var file_pluginhost_v1_pluginhost_proto_depIdxs = []int32{
	20, // 0: vastplan.pluginhost.v1.Hello.engines:type_name -> vastplan.pluginhost.v1.Hello.EnginesEntry
	3,  // 1: vastplan.pluginhost.v1.Declaration.contributions:type_name -> vastplan.pluginhost.v1.Contribution
	21, // 2: vastplan.pluginhost.v1.Registered.rejected:type_name -> vastplan.pluginhost.v1.Registered.RejectedEntry
	3,  // 3: vastplan.pluginhost.v1.RegisterContributions.contributions:type_name -> vastplan.pluginhost.v1.Contribution
	6,  // 4: vastplan.pluginhost.v1.UnregisterContributions.contributions:type_name -> vastplan.pluginhost.v1.ContributionRef
	22, // 5: vastplan.pluginhost.v1.ContributionUpdateAck.rejected:type_name -> vastplan.pluginhost.v1.ContributionUpdateAck.RejectedEntry
	23, // 6: vastplan.pluginhost.v1.InvokeRequest.target:type_name -> vastplan.contract.v1.CallTarget
	24, // 7: vastplan.pluginhost.v1.InvokeRequest.context:type_name -> vastplan.contract.v1.CallContext
	25, // 8: vastplan.pluginhost.v1.InvokeResponse.result:type_name -> vastplan.contract.v1.CallResult
	26, // 9: vastplan.pluginhost.v1.EventEnvelope.event:type_name -> vastplan.contract.v1.CallEvent
	0,  // 10: vastplan.pluginhost.v1.Lifecycle.op:type_name -> vastplan.pluginhost.v1.Lifecycle.Op
	4,  // 11: vastplan.pluginhost.v1.FromPlugin.declare:type_name -> vastplan.pluginhost.v1.Declaration
	11, // 12: vastplan.pluginhost.v1.FromPlugin.invoke_result:type_name -> vastplan.pluginhost.v1.InvokeResponse
	10, // 13: vastplan.pluginhost.v1.FromPlugin.host_call:type_name -> vastplan.pluginhost.v1.InvokeRequest
	12, // 14: vastplan.pluginhost.v1.FromPlugin.event:type_name -> vastplan.pluginhost.v1.EventEnvelope
	14, // 15: vastplan.pluginhost.v1.FromPlugin.lifecycle_ack:type_name -> vastplan.pluginhost.v1.LifecycleAck
	16, // 16: vastplan.pluginhost.v1.FromPlugin.pong:type_name -> vastplan.pluginhost.v1.Pong
	7,  // 17: vastplan.pluginhost.v1.FromPlugin.register:type_name -> vastplan.pluginhost.v1.RegisterContributions
	8,  // 18: vastplan.pluginhost.v1.FromPlugin.unregister:type_name -> vastplan.pluginhost.v1.UnregisterContributions
	17, // 19: vastplan.pluginhost.v1.FromPlugin.cancel:type_name -> vastplan.pluginhost.v1.Cancel
	5,  // 20: vastplan.pluginhost.v1.FromHost.registered:type_name -> vastplan.pluginhost.v1.Registered
	10, // 21: vastplan.pluginhost.v1.FromHost.invoke:type_name -> vastplan.pluginhost.v1.InvokeRequest
	11, // 22: vastplan.pluginhost.v1.FromHost.host_call_result:type_name -> vastplan.pluginhost.v1.InvokeResponse
	12, // 23: vastplan.pluginhost.v1.FromHost.event:type_name -> vastplan.pluginhost.v1.EventEnvelope
	13, // 24: vastplan.pluginhost.v1.FromHost.lifecycle:type_name -> vastplan.pluginhost.v1.Lifecycle
	15, // 25: vastplan.pluginhost.v1.FromHost.ping:type_name -> vastplan.pluginhost.v1.Ping
	9,  // 26: vastplan.pluginhost.v1.FromHost.contribution_update_ack:type_name -> vastplan.pluginhost.v1.ContributionUpdateAck
	17, // 27: vastplan.pluginhost.v1.FromHost.cancel:type_name -> vastplan.pluginhost.v1.Cancel
	1,  // 28: vastplan.pluginhost.v1.PluginHost.Handshake:input_type -> vastplan.pluginhost.v1.Hello
	18, // 29: vastplan.pluginhost.v1.PluginHost.Channel:input_type -> vastplan.pluginhost.v1.FromPlugin
	2,  // 30: vastplan.pluginhost.v1.PluginHost.Handshake:output_type -> vastplan.pluginhost.v1.HelloAck
	19, // 31: vastplan.pluginhost.v1.PluginHost.Channel:output_type -> vastplan.pluginhost.v1.FromHost
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_pluginhost_v1_pluginhost_proto_init() }
func file_pluginhost_v1_pluginhost_proto_init() {
	if File_pluginhost_v1_pluginhost_proto != nil {
		return
	}
	file_pluginhost_v1_pluginhost_proto_msgTypes[9].OneofWrappers = []any{}
	file_pluginhost_v1_pluginhost_proto_msgTypes[13].OneofWrappers = []any{}
	file_pluginhost_v1_pluginhost_proto_msgTypes[16].OneofWrappers = []any{}
	file_pluginhost_v1_pluginhost_proto_msgTypes[17].OneofWrappers = []any{
		(*FromPlugin_Declare)(nil),
		(*FromPlugin_InvokeResult)(nil),
		(*FromPlugin_HostCall)(nil),
		(*FromPlugin_Event)(nil),
		(*FromPlugin_LifecycleAck)(nil),
		(*FromPlugin_Pong)(nil),
		(*FromPlugin_Register)(nil),
		(*FromPlugin_Unregister)(nil),
		(*FromPlugin_Cancel)(nil),
	}
	file_pluginhost_v1_pluginhost_proto_msgTypes[18].OneofWrappers = []any{
		(*FromHost_Registered)(nil),
		(*FromHost_Invoke)(nil),
		(*FromHost_HostCallResult)(nil),
		(*FromHost_Event)(nil),
		(*FromHost_Lifecycle)(nil),
		(*FromHost_Ping)(nil),
		(*FromHost_ContributionUpdateAck)(nil),
		(*FromHost_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginhost_v1_pluginhost_proto_rawDesc), len(file_pluginhost_v1_pluginhost_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginhost_v1_pluginhost_proto_goTypes,
		DependencyIndexes: file_pluginhost_v1_pluginhost_proto_depIdxs,
		EnumInfos:         file_pluginhost_v1_pluginhost_proto_enumTypes,
		MessageInfos:      file_pluginhost_v1_pluginhost_proto_msgTypes,
	}.Build()
	File_pluginhost_v1_pluginhost_proto = out.File
	file_pluginhost_v1_pluginhost_proto_goTypes = nil
	file_pluginhost_v1_pluginhost_proto_depIdxs = nil
}
