// Code generated by engineering/tools/pluginrelease contracts; DO NOT EDIT.
export const uiContractVersion = "7.1.0" as const;
export const uiContractRange = "^7.0.0" as const;
export const uiContractMajor = 7 as const;
