// Code generated by engineering/tools/pluginrelease contracts; DO NOT EDIT.
export const uiContractVersion = "8.0.0" as const;
export const uiContractRange = "^8.0.0" as const;
export const uiContractMajor = 8 as const;
