// Code generated by engineering/tools/pluginrelease contracts; DO NOT EDIT.
export const uiContractVersion = "6.0.0" as const;
export const uiContractRange = "^6.0.0" as const;
export const uiContractMajor = 6 as const;
