import { message as localizedMessage, type LocalizedText } from "@vastplan/workbench-sdk";

export const namespace = "cn.vastplan.platform.infrastructure.deployment-manager";

export function message(key: string, fallback: string): LocalizedText {
  return localizedMessage(namespace, key, fallback);
}

export const messages = {
  "zh-CN": {
    "form.deployment": "部署目标", "form.services": "应用服务", "form.serviceClass": "服务分类", "form.serviceId": "服务 ID",
    "form.rootPlugins": "根应用插件", "form.pluginId": "插件 ID", "form.versionPolicy": "版本策略", "form.versionExact": "固定版本", "form.versionCompatible": "兼容升级", "form.version": "基准版本", "form.channel": "通道",
    "form.stable": "稳定版", "form.preview": "预发布", "form.testing": "测试版", "form.features": "启用 Feature", "form.pluginConfig": "插件配置",
    "form.replicas": "实例数", "form.autoscaling": "自动扩缩容", "form.minReplicas": "最小实例数", "form.maxReplicas": "最大实例数",
    "form.metric": "指标", "form.targetValue": "单实例目标值", "form.resources": "单实例资源请求", "form.cpuMillis": "CPU（毫核）",
    "form.memoryBytes": "内存（字节）", "form.gpu": "GPU 数量", "form.nodeSelector": "节点标签选择",
    "help.deployment": "目标及 Platform Profile 由平台运维预授权，不能在此修改。",
    "help.services": "这里只声明根插件、Feature、非敏感配置及容量意图；依赖、运行策略、状态模型和路由由 Planner 推导。",
    "help.versionPolicy": "固定版本始终使用指定版本；兼容升级按 SemVer caret 规则解析较新版本，0.x 的兼容边界更窄。", "help.features": "Feature 必须由插件签名 Manifest 预先声明。", "help.config": "以插件 ID 为键填写非敏感配置；密码和令牌必须通过凭证配置流程绑定。",
    "panel.intent": "应用意图", "panel.operations": "容量与放置", "panel.new": "新建应用意图草稿", "panel.edit": "编辑应用意图草稿",
    "action.new": "新建应用意图", "action.create": "创建草稿", "action.save": "保存草稿", "action.edit": "编辑",
    "action.refreshPlan": "重新解析计划", "action.submit": "提交审批", "action.approve": "批准", "action.publish": "发布",
    "action.rollback": "回滚到此版本", "action.resolution": "解析结果", "action.graph": "依赖图", "action.preview": "最终部署预览", "action.audit": "审计记录",
    "notice.created": "应用意图草稿已创建", "notice.saved": "应用意图草稿已保存",
    "confirm.submit": "提交前会再次调用 Planner；只有 Resolved 且未失效的计划才能进入审批。",
    "confirm.approve": "审批人与提交人必须不同，审批将绑定当前计划摘要。",
    "confirm.publish": "发布前会再次校验计划摘要，之后 Controller 才会调度 Node Agent。",
    "confirm.rollback": "回滚会从历史 Intent 创建并发布新的单调 revision。",
    "column.deployment": "部署", "column.status": "修订状态", "column.kind": "输入类型", "column.planStatus": "规划状态", "column.stale": "计划失效",
    "column.active": "活动", "column.updated": "更新时间", "column.unit": "服务单元", "column.serviceClass": "服务分类",
    "column.dependencies": "依赖服务", "column.capabilities": "依赖能力", "column.time": "时间", "column.action": "动作", "column.actor": "操作者",
    "status.draft": "草稿", "status.pendingApproval": "待审批", "status.approved": "已批准", "status.publishing": "发布中", "status.published": "已发布",
    "plan.resolved": "已解析", "plan.needsConfiguration": "待配置", "plan.invalid": "无效", "plan.legacy": "历史组合", "kind.intent": "Application Intent", "kind.legacy": "历史 Composition",
    "dialog.resolution": "Planner 只读解析结果", "dialog.graph": "派生服务依赖图", "dialog.preview": "内核校验后的 Deployment v2", "dialog.audit": "服务修订审计",
    "document.summary": "计划摘要", "document.features": "已启用 Feature", "document.providers": "Provider Binding", "document.configuration": "配置计划",
    "document.diagnostics": "诊断", "document.artifacts": "精确制品锁",
    "page.title": "服务与节点部署", "page.titleService": "服务与节点部署 · {service}",
    "page.description": "声明应用意图，由 Planner 派生依赖与运行策略，经审批后发布到 Node Agent 集群",
  },
  "en-US": {
    "form.deployment": "Deployment target", "form.services": "Application services", "form.serviceClass": "Service class", "form.serviceId": "Service ID",
    "form.rootPlugins": "Root application plugins", "form.pluginId": "Plugin ID", "form.versionPolicy": "Version policy", "form.versionExact": "Exact version", "form.versionCompatible": "Compatible updates", "form.version": "Baseline version", "form.channel": "Channel",
    "form.stable": "Stable", "form.preview": "Preview", "form.testing": "Testing", "form.features": "Enabled features", "form.pluginConfig": "Plugin configuration",
    "form.replicas": "Replicas", "form.autoscaling": "Autoscaling", "form.minReplicas": "Minimum replicas", "form.maxReplicas": "Maximum replicas",
    "form.metric": "Metric", "form.targetValue": "Target per replica", "form.resources": "Per-replica resource requests", "form.cpuMillis": "CPU (millicores)",
    "form.memoryBytes": "Memory (bytes)", "form.gpu": "GPU count", "form.nodeSelector": "Node selector",
    "help.deployment": "The target and Platform Profile are pre-authorized by platform operations.",
    "help.services": "Declare only root plugins, features, non-sensitive configuration, and capacity intent. Planner derives dependencies, runtime policy, state model, and routing.",
    "help.versionPolicy": "Exact always uses the selected version. Compatible updates follow SemVer caret rules, with narrower boundaries for 0.x releases.", "help.features": "Features must be declared by the signed plugin manifest.", "help.config": "Use plugin IDs as keys for non-sensitive values. Passwords and tokens must be bound through credential configuration.",
    "panel.intent": "Application intent", "panel.operations": "Capacity and placement", "panel.new": "New application intent draft", "panel.edit": "Edit application intent draft",
    "action.new": "New application intent", "action.create": "Create draft", "action.save": "Save draft", "action.edit": "Edit",
    "action.refreshPlan": "Resolve again", "action.submit": "Submit", "action.approve": "Approve", "action.publish": "Publish",
    "action.rollback": "Rollback to this revision", "action.resolution": "Resolution report", "action.graph": "Dependency graph", "action.preview": "Final deployment preview", "action.audit": "Audit log",
    "notice.created": "Application intent draft created", "notice.saved": "Application intent draft saved",
    "confirm.submit": "Planner runs again before submission. Only a fresh Resolved plan can enter approval.",
    "confirm.approve": "The approver must differ from the submitter. Approval binds the current plan digest.",
    "confirm.publish": "The plan digest is verified again before Controller schedules Node Agents.",
    "confirm.rollback": "Rollback creates and publishes a new monotonic revision from the historical Intent.",
    "column.deployment": "Deployment", "column.status": "Revision status", "column.kind": "Input type", "column.planStatus": "Plan status", "column.stale": "Plan stale",
    "column.active": "Active", "column.updated": "Updated", "column.unit": "Service unit", "column.serviceClass": "Service class",
    "column.dependencies": "Dependencies", "column.capabilities": "Capabilities", "column.time": "Time", "column.action": "Action", "column.actor": "Actor",
    "status.draft": "Draft", "status.pendingApproval": "Pending approval", "status.approved": "Approved", "status.publishing": "Publishing", "status.published": "Published",
    "plan.resolved": "Resolved", "plan.needsConfiguration": "Needs configuration", "plan.invalid": "Invalid", "plan.legacy": "Legacy composition", "kind.intent": "Application Intent", "kind.legacy": "Legacy Composition",
    "dialog.resolution": "Read-only Planner result", "dialog.graph": "Derived service dependency graph", "dialog.preview": "Kernel-validated Deployment v2", "dialog.audit": "Service revision audit",
    "document.summary": "Plan summary", "document.features": "Resolved features", "document.providers": "Provider bindings", "document.configuration": "Configuration plan",
    "document.diagnostics": "Diagnostics", "document.artifacts": "Exact artifact lock",
    "page.title": "Services and node deployment", "page.titleService": "Services and node deployment · {service}",
    "page.description": "Declare application intent, let Planner derive dependencies and runtime policy, then approve and publish to Node Agent clusters",
  },
} as const;
